### ISSUE TITLE
error: bit-add(1) does not exist

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2203] opened 2019-12-18 14:34 UTC
I am getting this weird error: 
```
error: bit-add(1) does not exist, try --help
```

I'm 90% sure it's because I tried to tag two components instead of using the `-a` tag, so it's probably ok, but the error message is really confusing.

to reproduce:
```bash
npx create-react-app typed --typescript > /dev/null

cd ./typed

bit init

echo '
import React from "react";

export default () => <div>
	I am CompA
</div>
' > ./src/a.tsx

echo '
import React from "react";

export default () => <div>
	I am CompB
</div>
' > ./src/b.tsx

echo '
import React from "react";
import CompA from "@bit/kutner.temp.a";
import CompB from "./b";

export default () => <div>
	<CompA />
	<CompA />
	I am CompC
</div>
' > ./src/ab.tsx

bit add ./src/a.tsx
bit add ./src/b.tsx

bit tag a b
```

console output:
```bash
❯ ./reproduce.sh
npx: installed 91 in 4.29s
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".                                    
We detected TypeScript in your project (src/App.test.tsx) and created a tsconfig.json file for you.

warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".                                    
successfully initialized a bit workspace.
tracking component a:
added src/a.tsx
tracking component b:
added src/b.tsx
error: version b is not a valid semantic version. learn more: https://semver.org
error: bit-add(1) does not exist, try --help
```

### Reference
  bit version   : 14.4.3
  node version  : v12.12.0
  npm version   : 6.13.4
  yarn version  : 1.19.1
  platform      : darwin

**Comment by itaymendel** [comment] 2019-12-18 14:41
your `tag` syntax does not match the [command synopsis](https://docs.bit.dev/docs/apis/cli-all#tag).
If you want to tag both components run `bit tag -a`. `tag` does not accept a list of arguments as components.

**Comment by GiladShoham** [comment] 2019-12-18 14:46
Actually it's because you can't name a component "a". It's commander parsing issue

**Comment by KutnerUri** [comment] 2019-12-18 15:03
@itaymendel - why am I getting error on ```bit-add``` when running ```bit tag```?
@GiladShoham - not the cause. I tagged component named 'a' before.

**Comment by davidfirst** [comment] 2019-12-18 19:03
As @GiladShoham mentioned. The problem is when tagging with the name "a".
@KutnerUri , here is the flow I just ran from my local:
```
➜  foo bit init
successfully initialized a bit workspace.
➜  foo touch a.js
➜  foo bit add a.js
tracking component a:
added a.js
➜  foo bit tag a
error: bit-add(1) does not exist, try --help
➜  foo
```
I came cross this bug numerous times (I have a habit to name my component `a.js`), we should fix it. I believe it's related to how Bit handles sub-commands of commanders.

**Comment by GiladShoham** [comment] 2019-12-18 22:07
@davidfirst @KutnerUri 
it's because `a` is the alias for the add command.
So when running `bit tag a`, commander thinks you tried to run `bit add` then you have missing args for the add command and you got the error.
we can solve it I believe by improve the parsing (maybe it's already solved in newer versions of commander)

**Comment by KutnerUri** [comment] 2019-12-18 22:13
😵

**Comment by GiladShoham** [comment] 2019-12-18 22:14
@KutnerUri feel free to take a look and try fixing it. I can point you where it should be. but it might as well be deep in the commander code which will make it very hard to solve.

**Comment by davidfirst** [comment] 2019-12-19 19:51
@GiladShoham , not entirely. If you run `bit add` with no args, you won't get the same error.
It's commander trying to parse "add" as a sub-command of "bit tag".
If you run `bit tag s`, you'll get the same error, although `bit status` doesn't need any args.

It seems like it has been fixed in v3 of commander:
https://github.com/tj/commander.js/issues/786

**Closed** 2021-03-07 14:46 UTC
Labels: priority/low, type/bug
