### ISSUE TITLE
bvm install got a fetch Error!

### ISSUE THREAD

**Issue by alzin** [teambit/bit#4208] opened 2021-04-30 05:11 UTC
I'm trying to install bit by following the documentation site but getting a fetching error with the second command!

npm i -g @teambit/bvm

/usr/local/bin/bvm -> /usr/local/lib/node_modules/@teambit/bvm/dist/app.js
npm WARN @teambit/time.time-format@0.0.298 requires a peer of react-dom@16.13.1 but none is installed. You must install peer dependencies yourself
.
npm WARN @teambit/time.time-format@0.0.298 requires a peer of @teambit/legacy@1.0.17 but none is installed. You must install peer dependencies you
rself.
npm WARN @teambit/time.time-format@0.0.298 requires a peer of react@16.13.1 but none is installed. You must install peer dependencies yourself.

@teambit/bvm@0.0.20
updated 1 package in 17.88s
bvm install

request to https://bvm.bit.dev/versions/dev/Darwin/0.0.377/bit-0.0.377.tar.gz failed, reason: connect ECONNREFUSED 127.0.0.1:443
FetchError: request to https://bvm.bit.dev/versions/dev/Darwin/0.0.377/bit-0.0.377.tar.gz failed, reason: connect ECONNREFUSED 127.0.0.1:443
at ClientRequest. (/usr/local/lib/node_modules/@teambit/bvm/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.socketErrorListener (_http_client.js:469:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

Local Environment:
MacBook Pro with macOS Big Sur
npm version: 6.14.11

**Comment by guysaar223** [comment] 2021-04-30 09:31
Hi, I think the problem is with your .dev resolver that referrer to your localhost.
try this: 
https://dev.to/brandonweiss/dev-domains-not-resolving-273b

**Comment by itaymendel** [comment] 2021-05-02 08:13
Closing the issue as this is a local DNS config issue.

**Closed by itaymendel** 2021-05-02 08:13 UTC
Labels: type/bug

**Comment by alzin** [comment] 2021-05-02 11:27
@guysaar223 

Thank you very much, that solution has solved the issue
