### ISSUE TITLE
Using flexible version constraints for other bit dependencies

### ISSUE THREAD

**Issue by rasmuscnielsen** [teambit/bit#2201] opened 2019-12-17 14:27 UTC
### Description

When having packages depend on each-other it would be neat to be able to use proper version-constraints rather than locking the dependency to a specific release. 
However, when attempting to use a loose version constraint I receive this error: 

`error: unexpected network error has occurred.  original message: error: version 0.1 is not a valid semantic version. learn more: https://semver.org`

This is my package.json. I've attempted several ways to define the version such as `~0.1.1`, `0.1.*`, `^0.1.1` etc. but nothing works.

![Skærmbillede 2019-12-17 kl  15 19 36](https://user-images.githubusercontent.com/8465957/71003072-cb12ee00-20e0-11ea-9bd5-efa0885fa351.png)

It makes it very hard to control updates when you have a big collection of packages with a lot of cross-dependencies. I would much rather just lock it to a major version, and then only have to deal with breaking changes.
Sometimes it also introduces unforeseeable bugs, when two packages are interacting with two different versions of the same package, because they have a different patch version defined :-( 

Am I missing something? 

### Specifications

- bit version   : 14.7.1
- node version  : v12.13.0
- npm version   : 6.12.0
- yarn version  : 1.19.1
- platform      : darwin

**Comment by KutnerUri** [comment] 2019-12-25 09:52
You might be able to solve this with [Overrides](https://docs.bit.dev/docs/overrides)
That said, bit should respect semvers from package.json. :(

**Comment by GiladShoham** [comment] 2019-12-25 11:43
@KutnerUri That's not accurate.

by design, bit doesn't allow flexible versions between components.
It's part of a much wider philosophy about how updates should work in an ideal world (semver is not good enough).
@rasmuscnielsen we will try to write a document that explains our philosophy. I don't know how much time it will take since it's a very complicated material. 
Also, we didn't yet implement most of that philosophy.
Anyway, this feature as is won't be implemented, we will come with a better (hopefully) method for dependencies updates.

@Tallyb Let's write this doc together.

**Closed by GiladShoham** 2019-12-25 11:43 UTC
Labels: type/help wanted

**Comment by rasmuscnielsen** [comment] 2020-07-02 09:29
@GiladShoham Any update on this? 

Unfortunately it's still a problem for us. The main thing is that when we make changes within a project by importing a component/package, it will only auto-tag dependencies that are also imported. Not dependencies that are just installed normally, nor other dependencies that exists in the collection but not used in the particular project.

This means that it's impractical to tag new versions within a project as dependencies will fall behind. As a result I've created a local project and imported our entire collection and only tagging changes here. But this kind of defeats the purpose of using Bit, and we might as well just use a mono-repo approach and have a single private npm package instead. 

I hope you'll consider offering some tooling to address this as we really like the idea behind Bit apart from this issue :-)

**Comment by GiladShoham** [comment] 2020-07-02 15:09
@rasmuscnielsen What you mention is a real use case. Actually our main focus as a company is about solving this issue in the product itself.
It's a whole new CI system we are working on, called Ripple CI.
Basically it will get your changed component and will trigger building and testing and tagging components for the entire graph of dependents in layers on the cloud (propagate from component to its dependent recursively). in the same collection, cross collection. 
with a visual graph dashboard and logs for each component and level, a place to discuss each change, and visually see what breaks and what works..
(There is much more, but it's too much to write about it here)
It's under development at the moment, and once it released I believe it will solve all your issues.
