### ISSUE TITLE
Yarn install get error Failed building all <user>.<scope>.components.login versions

### ISSUE THREAD

**Issue by hxuanhung** [teambit/bit#1017] opened 2018-05-28 16:24 UTC
## Expected Behavior
Install component successfully 

## Actual Behavior
Receive `error An unexpected error occurred: "https://node.bitsrc.io/@bit%2fhung-ww.ww-react-ui.components.login: Failed building all hung-ww.ww-react-ui.components.login versions"`

## Steps to Reproduce the Problem

  1. Here is my component: https://bitsrc.io/hung-ww/ww-react-ui/components/login/code
  1. Just try to install it via npm or yarn

## Specifications

  - Bit version: 0.12.13
  - Node version: 8.9.3
  - npm / yarn version: 1.3.2
  - Platform: macOS
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by hxuanhung** [comment] 2018-05-30 08:19
@davidfirst ok thank you for the information

**Comment by itaymendel** [comment] 2018-06-19 10:28
ok, i've validated it manually, and with the new upgrade to bitsrc's backend, the issue is now resolved.
closing this issue.

**Closed by itaymendel** 2018-06-19 10:28 UTC

**Comment by hxuanhung** [comment] 2018-06-25 08:16
Sorry for a late response. Yes I confirm it's fixed. Thank you.
