### ISSUE TITLE
Resolve custom tilde @import aliases in SCSS files

### ISSUE THREAD

**Issue by NielsJanssen** [teambit/bit#1103] opened 2018-06-26 08:10 UTC
I'm building a set of Vue components which come bundled with some SCSS, most of which import some global SCSS file. This works fine when importing using relative paths, but when using a resolver alias it doesn't.

## Expected Behavior
The following code should resolve the file when the `scss` alias is defined in the `resolveModules.aliases` section in the bit.json file.
```scss
@import "~scss/partials/palette";
```

## Actual Behavior
An error is thrown indicating the file can't be found.
```
error: bit failed to build ui/button@0.0.1 with the following exception:
Module build failed: 
@import "~scss/partials/palette";
^
      File to import not found or unreadable: ~scss/partials/palette.
```

## Steps to Reproduce the Problem

  1. Configure an alias to a directory containing SCSS files in bit.json
  1. Create an SCSS file importing another SCSS file using the configured alias (eg. `@import "~scss/colors";`)
  1. Import SCSS file from a JS file (eg. `import 'style.scss';`)

## Specifications

  - Bit version: 13.0.0
  - Node version: v10.5.0
  - npm / yarn version: 1.6.0
  - Platform: macOS 10.13.5
  - Bit compiler (include version): bit.envs/bundlers/vue@0.0.3
  - Bit tester (include version): -

## Possible solution?
Pass the resolve aliases to the compile function to allow it to deal with the aliased paths.

**Comment by itaymendel** [comment] 2018-06-26 08:56
Hi @NielsJanssen - this is supported using `resolveModules` configuration.
Please refer to [this doc](https://docs.bitsrc.io/docs/troubleshooting-isolating.html#configuring-custom-module-resolution) to understand how to configure the aliases.

Bit's next version will prompt a link to that part of the docs when it encounters any isolation error, so it will be easier to resolve :)

I'm closing this issue. If your problem persists, I'll reopen.

**Comment by itaymendel** [comment] 2018-06-26 08:59
oops, I misread the issue and closed it by mistake.

**Comment by GiladShoham** [comment] 2018-06-26 09:15
@davidfirst I believe this is an issue with the CSS detector (maybe we are not passing the resolve modules to this detector?)
We also need to verify that this case is working as expected after importing the component (make sure we won't create some double tilde in one of the files since we create binding files with tilde already)

**Comment by davidfirst** [comment] 2018-07-11 17:46
Some work was done around this last month and it's released already.
The behavior of Bit is very similar to Webpack. In short, there are two cases:

1. the name is right after the Tilda without a slash, e.g. `~scss/colors`. In this case, the Webpack Sass Loader tries to resolve the module from `node_modules. (see here for more info https://github.com/webpack-contrib/sass-loader).
2. there is a slash after the Tilda, e.g. `~/scss/color`. In this case, Bit will search the alias `~` inside the custom-resolve-modules configuration in bit.json. (see this Bit doc for more info https://docs.bitsrc.io/docs/troubleshooting-isolating.html#configuring-custom-module-resolution).

I'm closing the issue. Please reopen if the behavior is different than the two above.

**Comment by cadent-front-end** [comment] 2019-03-09 14:26
I just had a similar issue where bit wasn't recognizing a URL in my sass partial when I was trying to check the status
```
missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/styles/scss/static/_fonts.scss -> http:
```

I was using sass to import the following:

```scss
// src/styles/scss/static/_fonts.scss

@import "http://location-of-font-file.com"
```

I used the example above to create an alias that pointed back at the file and it seems to have been resolved:

New syntax:
```scss
// src/styles/scss/static/_fonts.scss

@import "fonts";
```

```js
// bit.json

{
  "resolveModules": {
    "aliases": {
      "fonts": "src/styles/scss/static/_fonts.scss"
    }
  }
}
```

**Comment by drewdecarme** [comment] 2019-03-09 14:38
I just had a similar issue where bit wasn't recognizing a URL in my sass partial when I was trying to check the status
```
missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/styles/scss/static/_fonts.scss -> http:
```

I was using sass to import the following:

```scss
// src/styles/scss/static/_fonts.scss

@import "http://location-of-font-file.com"
```

I used the example above to create an alias that pointed back at the file and it seems to have been resolved:

New syntax:
```scss
// src/styles/scss/static/_fonts.scss

@import "fonts";
```

```js
// bit.json

{
  "resolveModules": {
    "aliases": {
      "fonts": "src/styles/scss/static/_fonts.scss"
    }
  }
}
```

**Comment by GiladShoham** [comment] 2019-03-10 10:56
@drewdecarme Thanks for reporting this.
This is a bug, and we will fix it soon and update this issue.

**Comment by GiladShoham** [comment] 2019-03-13 12:58
@drewdecarme I couldn't reproduce your issue with the http.
Can you please create some gist / repo with all the necessary files to reproduce this?
Also please try with the latest version of bit (14.0.3).
Thanks

**Comment by drewdecarme** [comment] 2019-03-14 12:33
@GiladShoham I tried putting into a Gist to reproduce this, but it appears that after upgrading to `14.0.3` it seemed to be working. I have a Sass component that contained the same http import and hasn't gotten any errors so far!

I think I was on `14.0.1` when I reported my issue.

**Comment by GiladShoham** [comment] 2019-03-14 13:44
@drewdecarme Thanks for the update. closing.

**Closed by GiladShoham** 2019-03-14 13:44 UTC
Labels: area/dependencies, type/bug
