### ISSUE TITLE
Localhost UI does not show correct component version

### ISSUE THREAD

**Issue by ssidorovKG** [teambit/bit#5328] opened 2022-01-28 15:24 UTC
## Expected Behavior
When switching component version in localhost UI, Overview and Compositions tabs should show the selected version of the component

## Actual Behavior
When switching between versions of the component, Overview and Compositions tabs always show information for latest version only

## Steps to Reproduce the Problem
1. Create component with two versions
1. In localhost UI switch from latest version to the lower one
1. Observe Overview and Compositions tabs having information for the wrong version (latest instead of whatever is selected)

## Specifications
current (used) bvm version: 0.0.34
latest available bvm version: 0.0.34

current (used) bit version: 0.0.637
latest installed bit version: 0.0.637
latest available bit version: 0.0.637

* Node version: v14.16.0
* npm / yarn version: 7.20.3
* Platform: mac

Additional info: code explorer works fine, cloud version of the UI shows component versions as expected, only localhost version is not working

**Comment by GiladShoham** [comment] 2022-01-30 12:12
might be resolved by https://github.com/teambit/bit/pull/5330

**Comment by KutnerUri** [comment] 2022-01-31 18:20
I can confirm - bit only shows preview from the workspace itself, it doesn't have historical ones.
Not sure how it works.

**Comment by GiladShoham** [comment] 2022-02-01 15:59
Ok, I found the root cause of this issue. 
I'm working on it.
It's a bit tricky so might take some time. will update once ready.

**Closed** 2022-02-02 18:32 UTC
