### ISSUE TITLE
Imported Types not found 

### ISSUE THREAD

**Issue by williamluke4** [teambit/bit#1718] opened 2019-06-09 16:25 UTC
## Expected Behavior
Imports the Types and Uses them to generate your types

## Actual Behavior
Build Fails
```
error: issues found with the following component dependencies

select
missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
     src/select/components/Control.tsx -> react-select/lib/components/Control
     src/select/components/Menu.tsx -> react-select/lib/components/Menu
     src/select/components/MultiValue.tsx -> react-select/lib/components/MultiValue
     src/select/components/NoOptionsMessage.tsx -> react-select/lib/components/Menu
     src/select/components/Option.tsx -> react-select/lib/components/Option
     src/select/components/Placeholder.tsx -> react-select/lib/components/Placeholder
     src/select/components/SingleValue.tsx -> react-select/lib/components/SingleValue
     src/select/components/ValueContainer.tsx -> react-select/lib/components/containers
     src/select/index.tsx -> react-select/lib/Select
```

## Steps to Reproduce the Problem

  1. Import `react-select/lib/components/Control`
  1. Then Build the Component 
  1. Error

## Specifications

  - Bit version: 14.1.1
  - Node version: 10.5.0
  - npm version: 6.9.0
  - Platform: Windows
  - Bit compiler (include version):  react-typescript@3.04
  - Bit tester (include version): None

**Comment by itaymendel** [comment] 2019-06-10 08:16
Hi @williamluke4 , can you please assign me 'read' permissions to your content so I can take a look at the issue? my email is itay@bit.dev .

**Comment by williamluke4** [comment] 2019-06-10 09:36
It's the select component in `src` https://github.com/atto-byte/mui-daterange

**Comment by itaymendel** [comment] 2019-06-12 07:22
Hi @williamluke4 , on my mac I'm able to see the generated d.ts for `select`. I'll spin up a windows instance and see if your issue reproduces.

On a side note - you should not commit the `.bit` directory to the git repository.

**Comment by williamluke4** [comment] 2019-06-12 08:25
Thanks, I'm still trying to get my head around how to work with bit and git together

**Comment by GiladShoham** [comment] 2019-06-12 11:09
@williamluke4 
The issue has been resolved.
See this commit: https://github.com/teambit/bit.envs/commit/5c2df7e1555d86831ecee096e7d2c1666794f623
There is a new version of the react-typescript (3.0.6) with the fix.
All you have to do is to update the version.
I opened a PR for you:
https://github.com/atto-byte/mui-daterange/pull/1
Just take it and run `bit build` again.
(you can safely remove all the d.ts files in the wrong paths)
There is still a small issue with the output of the build command.
This is an issue with bit itself.
I opened a different issue about it [here](https://github.com/teambit/bit/issues/1725).
This shouldn't prevent you from working.

**Comment by williamluke4** [comment] 2019-06-12 12:45
Just tried again. Building works but then it fails when trying to tag a component

```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit build
successfully installed the bit.envs/compilers/react-typescript@3.0.6 compiler
(node:12884) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
atto-byte.components/date-range@0.0.5
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\Calendar.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\Calendar.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\Components.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\Components.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\DateRangePicker.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\DateRangePicker.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\DaySelect.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\DaySelect.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\MonthSelect.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\MonthSelect.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\YearSelect.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\YearSelect.js
dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\index.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\index.js
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\date-range\README.md

atto-byte.components/select@0.0.2
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Control.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Control.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Menu.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Menu.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\MultiValue.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\MultiValue.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\NoOptionsMessage.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\NoOptionsMessage.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Option.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Option.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Placeholder.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\Placeholder.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\SingleValue.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\SingleValue.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\ValueContainer.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\ValueContainer.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\index.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\index.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\inputComponent.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\components\inputComponent.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\index.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\index.js
dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\styles.js.map
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\styles.js
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\index.d.ts
D:\Documents\Atto-Byte\Projects\mui-daterange\dist\src\select\README.md


D:\Documents\Atto-Byte\Projects\mui-daterange>bit tag --all -mi
error: issues found with the following component dependencies

atto-byte.components/select@0.0.2
missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
     src/select/components/Control.tsx -> react-select/lib/components/Control
     src/select/components/Menu.tsx -> react-select/lib/components/Menu
     src/select/components/MultiValue.tsx -> react-select/lib/components/MultiValue
     src/select/components/NoOptionsMessage.tsx -> react-select/lib/components/Menu
     src/select/components/Option.tsx -> react-select/lib/components/Option
     src/select/components/Placeholder.tsx -> react-select/lib/components/Placeholder
     src/select/components/SingleValue.tsx -> react-select/lib/components/SingleValue
     src/select/components/ValueContainer.tsx -> react-select/lib/components/containersnon-existing dependency files (please make sure all files exists on your workspace): 
     src/select/index.tsx -> ./lib/Select

```

**Comment by GiladShoham** [comment] 2019-06-12 16:50
Can you try `bit status` and see if there are any issues there?

**Comment by williamluke4** [comment] 2019-06-12 17:37
```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > date-range ... ok
     > select ...  issues found
       missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/select/components/Control.tsx -> react-select/lib/components/Control
          src/select/components/Menu.tsx -> react-select/lib/components/Menu
          src/select/components/MultiValue.tsx -> react-select/lib/components/MultiValue
          src/select/components/NoOptionsMessage.tsx -> react-select/lib/components/Menu
          src/select/components/Option.tsx -> react-select/lib/components/Option
          src/select/components/Placeholder.tsx -> react-select/lib/components/Placeholder
          src/select/components/SingleValue.tsx -> react-select/lib/components/SingleValue
          src/select/components/ValueContainer.tsx -> react-select/lib/components/containers
          src/select/index.tsx -> react-select/lib/Select

see troubleshooting at https://docs.bit.dev/docs/troubleshooting-isolating.html
```

**Comment by williamluke4** [comment] 2019-06-13 06:53
```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > date-range ... ok
     > select ...  issues found
       missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/select/components/Control.tsx -> react-select/lib/components/Control
          src/select/components/Menu.tsx -> react-select/lib/components/Menu
          src/select/components/MultiValue.tsx -> react-select/lib/components/MultiValue
          src/select/components/NoOptionsMessage.tsx -> react-select/lib/components/Menu
          src/select/components/Option.tsx -> react-select/lib/components/Option
          src/select/components/Placeholder.tsx -> react-select/lib/components/Placeholder
          src/select/components/SingleValue.tsx -> react-select/lib/components/SingleValue
          src/select/components/ValueContainer.tsx -> react-select/lib/components/containers
          src/select/index.tsx -> react-select/lib/Select
```

**Comment by itaymendel** [comment] 2019-06-13 07:09
Try and run `bit link` to resolve the issue.

**Comment by williamluke4** [comment] 2019-06-13 07:13
```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit link
found 2 components
        atto-byte.components/date-range@0.0.6:
                original path: src/date-range/README.md, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\README.md
                original path: src/date-range/Calendar.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\Calendar.tsx
                original path: src/date-range/Components.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\Components.tsx
                original path: src/date-range/DateRangePicker.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\DateRangePicker.tsx
                original path: src/date-range/DaySelect.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\DaySelect.tsx
                original path: src/date-range/MonthSelect.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\MonthSelect.tsx
                original path: src/date-range/YearSelect.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\YearSelect.tsx
                original path: src/date-range/index.tsx, link path: node_modules\@bit\atto-byte.components.date-range\src\date-range\index.tsx
        atto-byte.components/select@0.0.3:
                original path: src/select/README.md, link path: node_modules\@bit\atto-byte.components.select\src\select\README.md
                original path: src/select/components/Control.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\Control.tsx
                original path: src/select/components/Menu.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\Menu.tsx
                original path: src/select/components/MultiValue.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\MultiValue.tsx
                original path: src/select/components/NoOptionsMessage.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\NoOptionsMessage.tsx
                original path: src/select/components/Option.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\Option.tsx
                original path: src/select/components/Placeholder.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\Placeholder.tsx
                original path: src/select/components/SingleValue.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\SingleValue.tsx
                original path: src/select/components/ValueContainer.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\ValueContainer.tsx
                original path: src/select/components/index.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\index.tsx
                original path: src/select/components/inputComponent.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\components\inputComponent.tsx
                original path: src/select/index.tsx, link path: node_modules\@bit\atto-byte.components.select\src\select\index.tsx
                original path: src/select/styles.ts, link path: node_modules\@bit\atto-byte.components.select\src\select\styles.ts

D:\Documents\Atto-Byte\Projects\mui-daterange>bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > select ...  issues found
       missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/select/components/Control.tsx -> react-select/lib/components/Control
          src/select/components/Menu.tsx -> react-select/lib/components/Menu
          src/select/components/MultiValue.tsx -> react-select/lib/components/MultiValue
          src/select/components/NoOptionsMessage.tsx -> react-select/lib/components/Menu
          src/select/components/Option.tsx -> react-select/lib/components/Option
          src/select/components/Placeholder.tsx -> react-select/lib/components/Placeholder
          src/select/components/SingleValue.tsx -> react-select/lib/components/SingleValue
          src/select/components/ValueContainer.tsx -> react-select/lib/components/containers
          src/select/index.tsx -> react-select/lib/Select

see troubleshooting at https://docs.bit.dev/docs/troubleshooting-isolating.html
```

**Comment by itaymendel** [comment] 2019-06-13 07:31
I re-initialized my windows setup and recloned the repo.
When I run `bit status` Bit tells me nothing is modified.
If there are any code modifications to the project - can you please push them to the repository?

**Comment by williamluke4** [comment] 2019-06-13 07:33
try the bit_fix branch

**Comment by itaymendel** [comment] 2019-06-13 08:06
Ok, now I see it.
The issue is that Bit is unable to resolve the absolute imports in your code without the proper configuration. In your `tsconfig` you have defined `paths`, so all imports that look like this `import { ControlProps } from 'react-select/lib/components/Control';`. Bit is unable to resolve it without a similar configuration.

The doc that the issue is referring to explains how to do it.
https://docs.bit.dev/docs/tracking-dependencies.html#custom-module-resolution

Another thing you can do is use the absolute paths Bit creates for each exported component, as shown [here](https://docs.bit.dev/docs/sourcing-components.html#importing-components-source-code)

**Comment by williamluke4** [comment] 2019-06-13 12:03
I have added this to my `tsconfig.json`
```
    "paths": {
      "react-select/lib/*": ["node_modules/@types/react-select/lib/*"]
    },
```
But now I am getting this error
```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit status
Invalid or unexpected token

D:\Documents\Atto-Byte\Projects\mui-daterange>bit build
Invalid or unexpected token

D:\Documents\Atto-Byte\Projects\mui-daterange>bit tag --all -mi
Invalid or unexpected token
```

**Comment by williamluke4** [comment] 2019-06-13 12:09
debug.log
```
2019-06-13T12:05:48.374Z - [31merror[39m: got an error from command status: SyntaxError: Invalid or unexpected token. Error serialized: {"stack":"C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\bit-javascript\\node_modules\\fs-extra\\lib\\empty\\index.js:1\n(function (exports, require, module, __filename, __dirname) { \n                                                              \n\nSyntaxError: Invalid or unexpected token\n    at new Script (vm.js:74:7)\n    at NativeCompileCache._moduleCompile (C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\v8-compile-cache\\v8-compile-cache.js:240:18)\n    at Module._compile (C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\v8-compile-cache\\v8-compile-cache.js:186:36)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)\n    at Module.load (internal/modules/cjs/loader.js:612:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:543:3)\n    at Module.require (internal/modules/cjs/loader.js:650:17)\n    at require (C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\v8-compile-cache\\v8-compile-cache.js:161:20)\n    at Object.<anonymous> (C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\bit-javascript\\node_modules\\fs-extra\\lib\\index.js:17:12)\n    at Module._compile (C:\\Users\\willi\\AppData\\Roaming\\npm\\node_modules\\bit-bin\\node_modules\\v8-compile-cache\\v8-compile-cache.js:192:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)\n    at Module.load (internal/modules/cjs/loader.js:612:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:543:3)\n    at Module.require (internal/modules/cjs/loader.js:650:17)","message":"Invalid or unexpected token"}
2019-06-13T12:05:49.030Z - [31merror[39m: [*] the command status has been terminated with an error code 1
```

**Comment by itaymendel** [comment] 2019-06-13 13:23
you should not copy it directly from your `tsconfig` to Bit.

Bit's configuration is a tad different. I linked to the relevant doc in my previous comment.
You can also look at the full bit config here - https://docs.bit.dev/docs/conf-bit-json.html#resolvemodules

**Comment by williamluke4** [comment] 2019-06-13 13:54
I am still receiving and I have tried everything. Do you have any suggestions  
```
D:\Documents\Atto-Byte\Projects\mui-daterange>bit build
Invalid or unexpected token
```

**Comment by itaymendel** [comment] 2019-06-13 13:55
can you please commit and push the changes to your repo?

**Comment by williamluke4** [comment] 2019-06-13 13:58
Ok I have just pushed to the bit_fix branch

**Comment by williamluke4** [comment] 2019-06-13 14:05
I could share my vs code session with you

**Comment by itaymendel** [comment] 2019-06-13 14:45
hi @williamluke4 , can you ensure that the project runs regardless of the Bit commands and workflow?

There are a few issues I'm seeing just by looking into the code:

1. you are importing only the types in your components, not the actual code:
in `menu.tsx`:
```js
import { MenuProps } from 'react-select/lib/components/Menu';
```
and `react-select/lib/` is defined in the `tsconfig` like so:
```
"react-select/lib/*": ["node_modules/@types/react-select/lib/*"]
```
I'm not sure this can work, as you need to import the library, and then the type definitions are something the IDE's language services bring. You can revert it back to the relative require as it was in the master branch.

2. There are git merge markers committed to some of the files (`.bitmap`, and `menu.tsx`). This makes Bit fail when it tries to read from the `bitmap` file (hence the build issue you see), and once fixed, Bit fails to get the dependencies correctly from `menu`, as the entire process fails when Bit tries to parse the code.

Until these issues are corrected, there is no way Bit can track components.

**Comment by itaymendel** [comment] 2019-06-13 16:14
The main dependencies issue in the branch bit_fix is because it has an alias on top of an absolute path.
This type of configuration is not supported in Bit right now.
If you change the import statement to be the full, absolute one, Bit will be able to resolve the dependency correctly.

As for the `.bitmap` issue - i think there's an invisible char written into it by mistake. I recopied it from the raw format github shows in its web ui, and the invalid json issue was resolved.


I'm closing this issue.
If you want, please open a separate feature request for Bit to support using `resolveModules` absolute paths on top of another absolute path. (in this case, it was to shorten a file import from a node_module).

**Closed by itaymendel** 2019-06-13 16:14 UTC
Labels: area/envs, priority/high, type/bug
