### ISSUE TITLE
Handling import files with a dot (.) in their name

### ISSUE THREAD

**Issue by yourownmood** [teambit/bit#1047] opened 2018-06-08 13:36 UTC
## Expected Behavior
When trying to import a node_module (or local file) with a dot in the name, for example:
```
@import "../../node_modules/inuitcss/settings/settings.core.scss";
```
It should resolve the path to the node_module correctly.

## Actual Behaviour
It can't find the file reference.

## Steps to Reproduce the Problem

Changing the import statement to
```
@import "../../node_modules/inuitcss/settings/settings-core.scss";
```
And changing the node_module file name (not recommended) from `settings.core.scss` => `settings-core.scss`
Works! And proves that the path and bit setup is correct.

## Specifications

  - Bit version: 0.12.13
  - Node version: v8.9.3
  - npm / yarn version: 1.3.2
  - Platform: OSX
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment] 2018-06-12 15:09
hi @yourownmood , thanks for posting the issue. I will take a look at it and see when this can be implemented.

**Comment by itaymendel** [comment] 2018-08-23 10:59
from what I see, the issue is with tracking files from within the node_modules.
I don't think that this is something we want to support when tracking files with Bit, so i'm closing this issue.

**Closed by itaymendel** 2018-08-23 10:59 UTC

**Comment by yourownmood** [comment] 2018-08-28 05:59
It happens when i want to track a file in my bit project which has a dependency with a node_module file.

Simple example of my main.scss i would like to include, shows an error that it cant find the file reference

‘’’
@import "../../node_modules/inuitcss/settings.core.scss

body {
  color: red;
}
‘’’
