### ISSUE TITLE
Confusing message returned on bit commands when directories are moved

### ISSUE THREAD

**Issue by jlineberry-ventera** [teambit/bit#4209] opened 2021-04-30 15:54 UTC
### Describe the bug

A clear and concise description of the issue.
- I'm receiving a confusing warning after running _any_ `bit` command. It always says something about 'no files to add' as if I'm running a `bit add` command. 

### Steps to Reproduce

1. I manually moved a directory  (i.e. `./src/components` -> `./components`)
2. I ran a bit command (i.e. `bit status` or `bit compile`) and received this warning message:
- ![image](https://user-images.githubusercontent.com/71463916/116719668-583ea600-a9a9-11eb-8404-bea6ef376925.png)

### Expected Behavior

- I expected something more relevant to the command I entered, or at least something explaining _why_ that message is appearing.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.
 ![image](https://user-images.githubusercontent.com/71463916/116719668-583ea600-a9a9-11eb-8404-bea6ef376925.png)

### Specifications

- Bit version: 0.377
- Node version: 15.14.0
- npm / yarn version: yarn 1.22.5
- Platform: macOS
- Bit compiler (include version): not sure 
- Bit tester (include version): not sure

**Comment by GiladShoham** [comment] 2021-05-04 10:30
In general we should identify that the folder does not exist then:
1. change the error message to say that folder is missing, and might be moved. suggest you to run bit move command
2. when running bit move command we should see that the folder is already in the new location and only update the bitmap

**Comment by davidfirst** [comment] 2021-05-04 18:27
This is the same issue as https://github.com/teambit/bit/issues/4015.
As you can see in that issue, there are two more reasons for this error:
1. switching between git branches.
2. adding the component directory to .gitignore file.

The error message needs be adjusted accordingly. 
@GiladShoham , I think this is a regression since the files were removed from the .bitmap file and resolved during the bootstrap of BitMap instance.

**Comment by davidfirst** [comment] 2021-05-05 20:04
Fixed by https://github.com/teambit/bit/pull/4225.

**Closed by davidfirst** 2021-05-05 20:04 UTC
Labels: type/bug
