### ISSUE TITLE
TypeError: item.startsWith is not a function

### ISSUE THREAD

**Issue by idealley** [teambit/bit#848] opened 2018-03-15 16:18 UTC
## Expected Behavior
It should tag a version

## Actual Behavior
I might have done something wrong because it is the first time that I am using bit but I have the following error when I do `bit tag --all` or other bit methods:

```
TypeError: item.startsWith is not a function
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/dist/dependency-builder/build-tree.js:238:14
    at XWrap.f (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6290:23)
    at XWrap.@@transducer/step (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5203:46)
    at _reduce (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:5233:24)
    at reduceBy (/Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:6289:16)
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:586:23
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:551:35
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:52:27
    at /Users/samuel/.nvm/versions/node/v9.8.0/lib/node_modules/bit-bin/node_modules/bit-javascript/node_modules/ramda/dist/ramda.js:429:80
It does the same error with other node versions.
```

I could start tracking `.vue` component with `bit add src/components/folder/*.vue` They have been added to the `bit.json` but then anything else I do generates this error.

## Steps to Reproduce the Problem

  1. Install bit
  1. Start tracking compoonents
  1. Try to tag them

## Specifications

  - Bit version: 0.12.9
  - Node version: 9.8.0 / 8.4.0
  - npm / yarn version: npm 5.6.0
  - Platform: Mac
  - Bit compiler (include version): I am not sure what this is
  - Bit tester (include version): Nor that.

**Comment by amitgilad3** [comment] 2018-03-15 16:21
Hi @idealley .
Vue files are supported by bit, so i want to try and debug your issue locally.
can you please share the project with me privately so i can try to recreate this issue?

**Comment by idealley** [comment] 2018-03-15 16:25
Hello, thank you!

Actually there is nothing secret. I just pushed it (with the bit config files) https://github.com/EuropeanRespiratorySociety/search

**Comment by amitgilad3** [comment] 2018-03-15 16:41
thanks @idealley .
 i was able the reproduce the issue. will check to see the root cause and fix it :)

**Comment by idealley** [comment] 2018-03-15 16:42
Cool, that's nice when we can reproduce ;)

**Comment by GiladShoham** [comment] 2018-03-19 14:10
@idealley This issue has been resolved as part of https://github.com/teambit/bit/pull/857
it will be part of the next bit version

**Comment by GiladShoham** [comment] 2018-03-21 17:09
@idealley This should be ok now with the new 0.12.10 release.

**Closed by GiladShoham** 2018-03-21 17:09 UTC
