### ISSUE TITLE
missing dependencies from compiler API

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1759] opened 2019-06-25 13:37 UTC
### Describe the bug
When trying to isolate and compile the [accordion](https://github.com/primefaces/primeng/tree/master/src/app/components/accordion) component in [primng](https://github.com/primefaces/primeng) I don't get some of the dependencies in the `componentObject` passed to the compiler, while I do get them in the package.json in the capsule. 

A clear and concise description of the issue.

### Steps to Reproduce

  1. Create a custom compiler which prints out the dependencies passed to it's run-time.
  2. Compare them to the package.json in the capsule.
  3. Notice that zone.js appears in the package.json and not in the printed list

### Expected Behavior
get a full list of the dependencies.
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

  - Bit version: 14.1.4-dev.4
  - Node version: 12.3.1
  - npm / yarn version:  6.9.0
  - Platform: Ubuntu
  - Bit compiler (include version): Custom
  - Bit tester (include version): N/A

**Comment by davidfirst** [comment] 2019-07-04 17:12
Turned out that the symlink of node_modules/@bit/accordion to the capsule root was the cause of packages disappears from node_modules.
It has been fixed on PR https://github.com/teambit/bit/pull/1777.

**Closed by davidfirst** 2019-07-04 17:12 UTC
Labels: type/bug
