### ISSUE TITLE
bit tag fail when test file use jest.mock to mock a component

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4843] opened 2021-09-02 09:12 UTC
I mocked the child component in my test file like below:

```
jest.mock('./rangeSlider.jsx', () => ({
  __esModule: true,
  default: () => <input type="range" />
}));
```

it runs success when I execute `yarn jest`
but when I tag this component, it gave me an error.

   `Note: This is a precaution to guard against uninitialized mock variables.
 If it is ensured that the mock is required lazily, variable names prefixerseFloat, parseInt, process,
 queueMicrotask, red with `mock` (case insensitive) are permitted.`
![image](https://user-images.githubusercontent.com/40735433/131816388-2869f77d-3d65-4751-8eca-d38e5c3e2ef7.png)

of course, we can't use React in `jest.mock`,  I think it's a problem related to compile

**Comment by sbland** [comment] 2021-12-03 13:15
Also having this problem. Is there a way we can modify the build pipeline in a custom environment?

**Comment by dfortem** [comment] 2023-01-10 15:02
I am having the same issue a year later... Any one found a workaround in the mean time?

**Comment by sbland** [comment] 2023-01-10 20:20
I currently have to use `--skip-tests` or just avoid mocks that reference React. Unfortunately I just had the same issue with the below code that used async...

```
jest.mock('./demo-api', () => ({
  asyncFileUpload: jest.fn().mockImplementation(async () => {}),
}));
```
Gets transcribed to 
```
  39 | jest.mock('./demo-api', () => ({
> 40 |     asyncFileUpload: jest.fn().mockImplementation(() => __awaiter(void 0, void 0, void 0, function* () { })),
     |                                                         ^^^^^^^^^
  41 | }));
```

**Comment by sbland** [comment] 2023-01-11 17:12
A possible workaround is to mock it as `jest.fn()`. Then import the object and update the mock in `beforeAll`.

**Comment by benjgil** [comment] 2023-01-15 10:53
Looks like a general issue with jest.mock of functions, not so much to do with bit
https://stackoverflow.com/questions/44649699/service-mocked-with-jest-causes-the-module-factory-of-jest-mock-is-not-allowe/64427443#64427443

**Comment by sbland** [comment] 2023-01-18 09:13
I think the issue is that you can write tests that pass pre build but not post build. Even using async in a call causes it to fail. This seems to be because bit runs the tests after the code is compiled and the compiled code breaks the jest out of scope variable rule.

**Comment by NitsanCohen770** [comment] 2023-08-28 21:42
This is resolved with the new env api.

**Closed by NitsanCohen770** 2023-08-28 21:42 UTC
Labels: type/bug
