### ISSUE TITLE
Jest and ES6 keyword import

### ISSUE THREAD

**Issue by mrnagydavid** [teambit/bit#1346] opened 2018-12-06 13:22 UTC
## Expected Behavior
Jest runs the test without having to compile the (test) code to ES5.

## Actual Behavior
Jest does not run the test because it fails on the `import` keyword.
```
Test suite failed to run 
      ● Test suite failed to run
    /tmp/5bf052071b655e0012853b18/environment/1c863b03-a0dc-4bb2-b5b4-aa4886ba50ca/index.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import {
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
      at ScriptTransformer._transformAndBuildScript (../../components/testers/jest/bit.envs/0.0.34/node_modules/jest-runtime/build/script_transformer.js:316:17)
```

## Steps to Reproduce the Problem

  1. Create a component to upload to bit.
  1. Create a test file that imports the tested function with `import` instead of `require`
  1. Import bit component jest as tester (which includes babel)
  1. After `bit add <component>` run `bit test` or `bit tag`

## Specifications

  - Bit version: 13.0.4
  - Node version: 11.1.0
  - npm / yarn version: 1.12.3
  - Platform: MacOS
  - Bit compiler (include version): -
  - Bit tester (include version): jest@0.0.34

Or at least how can I remove the tester from the project? I added it with `bit import`, but `bit remove` does not seem to work.

**Comment by GiladShoham** [comment] 2018-12-06 15:18
@mrnagydavid Thanks for reporting this.
Currently in bit, a tester will run on the compiled files. So the best way to solve the issue is probably to add a bit compiler to your project, like babel or webpack, read more [here](https://docs.bitsrc.io/docs/building-components.html).

If you want to remove the tester, you can edit the bit.json file in the root of your workspace and remove the tester entry.

In the future we will add an option to run the tester on the source files in case your tester run's build himself.

I'm closing this, since this is the expected behaviour. 
Let us know if you need any further help.

**Comment by ArtemKorchunov** [comment] 2019-09-25 08:36
Adding compiler does not help me, and the one strange thing that I faced was that tests run successfully in local with the command `bit test ui/add-button` but fails remotely

### Actual behavior

      ● Test suite failed to run

    /workspace/environment/47aab6bb-1257-47bf-bc96-7213ffb5d536/addButton.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (../../components/testers/jest/bit.envs/22.4.3/node_modules/jest-runtime/build/script_transformer.js:316:17)`

### Steps to reproduce

1. Create a component to upload to bit.
2. Create a test file that imports the tested function with import instead of require
3. Import bit component jest as tester (which includes babel)
4. Import bit component react as compiler (which includes babel)
5. Export component

### Specifications

- Bit version: 14.0.4
- Node version: 10.15.2
- npm / yarn version: 6.11.3 / 1.17.3
- Platform: Linux
- Bit compiler (include version): react@1.0.2
- Bit tester (include version): jest@22.4.3

**Comment by GiladShoham** [comment] 2019-09-25 09:15
Hi, I'm re-open this issue.
Can you please create a simple repo / bit collection to reproduce this issue?
We are working on a new piece of tech which will make all the compilers / testers to be much more stable between the local and the remote.
This involves also re-writing all of our compilers and testers.
So it will take some time.
But we might solve this issue specifically on the existing version.

**Comment by ArtemKorchunov** [comment] 2019-09-25 09:55
Yeah, sure, here it is https://bit.dev/artemkorchunovv/test1/ui/add-button/~console

**Comment by VCuzmin** [comment] 2020-10-21 09:58
I've come across this issue too.  This is because you might have compiled your code into ES modules and Jest just doesn't have ES6 support. Take a look over here: https://github.com/facebook/jest/issues/4842

**Comment by itaymendel** [comment] 2021-03-07 12:48
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Closed by itaymendel** 2021-03-07 12:48 UTC
Labels: area/envs, type/bug
