### ISSUE TITLE
Test files break the build

### ISSUE THREAD

**Issue by jackguoAtJogg** [teambit/bit#2173] opened 2019-12-04 20:32 UTC
### Build error

I ran into issues where my test files would get build when I run `bit build [component name]`. This would cause my build to fail and I couldn't run the test properly. 

### Steps to Reproduce

1. Add a component with a test
1. Run `bit build [component]`
1. You should see compile error

### Expected Behavior

It should build the component correctly and I should be able run the test.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/56273621/70178966-04377100-1692-11ea-9d70-d8f99ad035b5.png)
![image](https://user-images.githubusercontent.com/56273621/70178948-fb469f80-1691-11ea-9cae-f16f19395ba7.png)

### Specifications

- Bit version: 14.6
- Node version: 10.16.3
- npm / yarn version: 1.19.1
- Platform: Next.js
- Bit compiler (include version): react-typescript@3.0.30
- Bit tester (include version): jest@22.4.3

**Comment by GiladShoham** [comment] 2019-12-05 09:25
@jackguoAtJogg Thanks for reporting this.
This is not a bug, it's by design.
You can read a bit more about the rationale behind building the test files here - https://github.com/teambit/envs#testing
Regarding the error, you faced when building the test file, it's a missing dependency (@types/jest I guess, can't see the full error in the screenshot attached) . 
It's missing because you never require it so bit couldn't recognize it automatically. 
In order to solve it, you should add this dependency to your component using the [overrides feature](https://docs.bit.dev/docs/overrides#components-dependencies).
you can also read more about it in the FAQ of the [typescript](https://bit.dev/bit/envs/compilers/typescript) compiler.
Ideally, this should be added automatically by your bit compiler/tester. We are working to implement this automation so you won't have to manually add it to the overrides.
I'm closing this issue since it's not a bug, if you face more issues regarding building/testing, it's better to open them in the [envs repo](https://github.com/teambit/envs).

**Closed by GiladShoham** 2019-12-05 09:25 UTC
Labels: type/bug

**Comment by jackguoAtJogg** [comment] 2019-12-06 01:14
Okay, I'll try it. Thank you for the help!
