### ISSUE TITLE
Critical dependency warning in angular

### ISSUE THREAD

**Issue by gvmohzibat** [teambit/bit#2233] opened 2020-01-08 16:43 UTC
### Describe the bug

I created my first component in bit which is an Angular directive named "loader".
The structure is simple:
```
loader/
    loader.directive.ts
    loader.module.ts
```

I then installed it in my other angular project and ran the project. Now I get this warning twice:

```
WARNING in ./node_modules/@bit/pegahco.angular.loader/node_modules/@angular/core/fesm5/core.js 27316:15-36
Critical dependency: the request of a dependency is an expression
```

### Specifications

- Bit version: 14.7.1
- Node version: 10.16.3
- npm / yarn version: 6.12.0
- Platform: Ubuntu
- Bit compiler (include version): angular@0.2.0
- Bit tester (include version): ?
- Angular version: Angular@8.2.x

**Comment by GiladShoham** [comment] 2020-01-13 09:19
Thanks @gvmohzibat 
Is there a chance you can share your source code?

**Comment by gvmohzibat** [comment] 2020-01-26 09:17
@GiladShoham Without doing anything (And I really mean anything) the problem was solved. Now the code is [available in bit](https://bit.dev/pegahco/angular/directives/loader/~code#directives/loader/loader.directive.ts)

**Comment by GiladShoham** [comment] 2020-01-26 09:34
@gvmohzibat Thanks for the update.
I'll close it for now, since it's now working and there is no easy way to reproduce it.
If it happens again, please re-open.
Thanks.

**Closed by GiladShoham** 2020-01-26 09:34 UTC
Labels: type/bug
