### ISSUE TITLE
Webpack CSS Module not showing under Files

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1325] opened 2018-11-11 10:49 UTC
## Expected Behavior
Here https://bitsrc.io/mrkhanakia/jeoga/auth/loginform/code under Files Sidebar it should show 
just like that https://bitsrc.io/bit/movie-app/components/hero-button/code **webpack-css-modules**

BIT JSON FILE
[bit.json.txt](https://github.com/teambit/bit/files/2569263/bit.json.txt)
## Actual Behavior
Not showing webpack-css-modules even i have imported the envs

## Steps to Reproduce the Problem

  1. bit import bit.envs/bundlers/webpack-css-modules
  2. bit tag --all
  3. bit export mrkhanakia.jeoga

```
khanakias-MacBook-Pro:client khanakia$ bit import bit.envs/bundlers/webpack-css-modules --override

successfully ran npm install at /Volumes/D/www/js/jeoga_market/client/components/bundlers/webpack-css-modules 

successfully imported one component
- up to date bit.envs/bundlers/webpack-css-modules  
khanakias-MacBook-Pro:client khanakia$ bit tag --all
nothing to tag
khanakias-MacBook-Pro:client khanakia$ bit export mrkhanakia.jeoga
nothing to export

```
## Specifications

  - Bit version: 13.0.4 
  - Node version: v10.11.0

  - npm / yarn version: 6.4.1
  - Platform: OSX
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment] 2018-11-11 11:03
Hi @mrkhanakia ,
Thanks for reporting this.
The issue is a result of importing the webpack-css-modules as regular component instead of as compiler.
When importing it you should add the --compiler flag.
`bit import bit.envs/bundlers/webpack-css-modules --compiler`
Then tag and re-export.
See more here:
https://docs.bitsrc.io/docs/cli-import.html#import-a-new-environment
Closing this.

**Closed by GiladShoham** 2018-11-11 11:03 UTC

**Comment by mrkhanakia** [comment] 2018-11-11 11:09
I just did as you said now it removed the react compiler so how do i import multiple compiler
**bit import bit.envs/compilers/react -c**
When i import any compiler it removes the previous one.

**Comment by GiladShoham** [comment] 2018-11-11 11:45
Configuring multiple compilers for components originated from the same workspace is not yet available. I'm implementing this workflow as we speak, and it will be GA in the near future.

Is there a reason why you would need such support right now? I can try and think about possible workarounds, depends on what you try to do with Bit.

**Comment by mrkhanakia** [comment] 2018-11-11 11:53
I needed to compile Sass and React js but i see the webpack compiler you are providing it does both so i do not need Multiple compiler support. That's fine for now.

Thanks
