### ISSUE TITLE
bit dep resolution warns about missing peerDeps

### ISSUE THREAD

**Issue by remy** [teambit/bit#1286] opened 2018-10-18 12:34 UTC
## Expected Behavior

bit import <id> should install dependencies without (invalid) warnings.

## Actual Behavior

(See steps to reproduce for full detail) - 

<img width="1280" alt="screen shot 2018-10-18 at 12 54 51" src="https://user-images.githubusercontent.com/13700/47154436-3cd38a00-d2da-11e8-87a5-ac034ce702c5.png">

## Steps to Reproduce the Problem

  1. Create component that has peerDependencies in it's package.
  1. Create separate project that will `import` component from (1), and install required peerDependencies (as production deps)
  1. Run `bit import <id>` and warnings are thrown via npm.

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.9.1
  - npm version: 6.1.0
  - Platform: OSX
  - Bit compiler (include version): unsure how to find out
  - Bit tester (include version): unsure how to find out

**Comment by davidfirst** [comment] 2018-10-19 14:32
The problem is that NPM doesn't have the concept of workspaces, so when Bit npm installs packages on `root/components/message`, npm doesn't aware that `root/package.json` has the peer dependency already.

I'm wondering what would be the best fix for this.
One option is to read the package.json of the component, look for the peer dependencies, search them in the root package.json (in the dependencies section) and if there is a match, suppress the warning.

**Comment by itaymendel** [comment] 2021-03-07 12:50
workspace dependencies (with peer) is resolved in v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Closed by itaymendel** 2021-03-07 12:50 UTC
Labels: area/dependencies, priority/low, type/bug
