### ISSUE TITLE
Bit not tracking files without extensions

### ISSUE THREAD

**Issue by xerosanyam** [teambit/bit#1659] opened 2019-05-22 01:29 UTC
## Expected Behavior
Track files without extension

## Actual Behavior
Is not able to track file where extension is not present
 
## Steps to Reproduce the Problem
In Vue
  1. import Popover from "./../Popover/Popover";
  2. Bit won't be able to track it.
  3. import Popover from "./../Popover/Popover.vue";
  4. Now bit will be able to track

## Specifications

  - Bit version: 14.1.0
  - Node version: 8.12.9
  - npm / yarn version: 6.5.0
  - Platform: Vue
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by davidfirst** [comment] 2019-05-22 23:24
@xerosanyam , what do you mean by "not able to track"?

I tried to create the following workspace:
```
├── bit.json
└── src
    ├── Menu
    │   └── Menu.vue
    └── Popover
        └── Popover.vue
```
the file `src/Menu/Menu.vue` has the following content:
```
<script>
import Popover from "./../Popover/Popover";
</script>
```
when I add the Menu (`bit add src/Menu`) and run `bit status` I get:
```
> menu ...  issues found
       untracked file dependencies (use "bit add <file>" to track untracked files as components):
          src/Menu/Menu.vue -> src/Popover/Popover.vue
```
which proves that Bit is able to resolve the dependency correctly.

**Comment by xerosanyam** [comment] 2019-05-23 09:18
which version did you use to test this?
Because I am on latest version but it was unable to perform this

in Vue
<template src="./header.html'>
</template>

here header isn't tracked too.

**Comment by davidfirst** [comment] 2019-05-23 13:43
@xerosanyam , what do you mean by " it was unable to perform this"? Did you get any error when you run `bit add` or `bit status`? if so, please paste the error here.

I was using the latest version as well.

**Comment by itaymendel** [comment] 2020-10-12 13:49
closing as unable to reproduce the issue locally.

**Closed by itaymendel** 2020-10-12 13:49 UTC
Labels: area/dependencies, type/help wanted
