### ISSUE TITLE
paper completion

### ISSUE THREAD

**Issue by ranm8** [teambit/bit#2691] opened 2020-05-20 16:35 UTC
As discussed, we have few issues to settle re Paper:

- Type signature for render function is very hard to work with.
- Can't use Paper components after requiring them from separate files.
- Merge CLI and Paper to the same extension called CLI.
- Make sure Command exposes both `render` and `report` commands and deciding default by checking for `process.stdout.isTTY`

**Comment by qballer** [comment] 2020-06-10 09:22
> As discussed, we have few issues to settle re Paper:
> 
> * Type signature for render function is very hard to work with.
Can you please share more details on the issues? 

> * Can't use Paper components after requiring them from separate files.
The problem is that the render function is part of the command, You require a command. I will make it a property you provide the command and the component will be independent 
> * Merge CLI and Paper to the same extension called CLI.
Cool.
> * Make sure Command exposes both `render` and `report` commands and deciding default by checking for `process.stdout.isTTY`
Cool.

**Closed** 2021-03-07 15:35 UTC
Labels: type/bug
