### ISSUE TITLE
[harmony] windows EOL explosion in 

### ISSUE THREAD

**Issue by drkstr101** [teambit/bit#4040] opened 2021-04-01 01:41 UTC
Just a heads up, every time the `bit` command triggers a repaint of `workspace.jsonc` on windows appends an additional `\n|\r` (windows EOL) for every EOL that already exists, leading to some fairly lengthy line numbers.

If someone who has done some slight work in the field of grammar parsers were curious to have a peek at your implementation of this, where might that someone look?

PS: Usually have Ubuntu as my daily driver so please let me know if I just did something silly that would cause this, but it does seem to be limited to this specific usage.

bit version: `nightly`

**Comment by itaymendel** [comment] 2021-04-01 10:18
hi @drkstr101 
it's actually an issue we've being trying to hunt down, as we're not able to reproduce it properly.

@davidfirst @GiladShoham 
perhaps you can share some more info?

**Comment by GiladShoham** [comment] 2021-04-01 16:05
I'm wondering if it happens on specific windows terminal only?

**Comment by drkstr101** [comment] 2021-04-01 19:15
Ah, very interesting!

One thing that comes to mind... Mixed line endings. The original file was created in Linux, then later updated in Windows in both eclipse and VSCode, possibly with inconsistent settings. .jsbeatutifyrc is set to lf, so let me see if running this puts a stop to it. 

Also, multiple terminals were used in the process, randomly and for no specific reason. I will do some testing to see if I can narrow it down to a specific configuration.

**Comment by GiladShoham** [comment] 2021-04-04 10:30
@drkstr101 If you will be able to narrow it down to consistent reproduction steps it will be really great.
Thanks a lot!

**Comment by davidfirst** [comment] 2021-04-08 17:09
I was able to find the root cause of this issue, it has been fixed on https://github.com/teambit/bit/pull/4084.

**Closed** 2021-04-08 18:40 UTC
Labels: type/bug
