### ISSUE TITLE
bad output when failing to find file

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1649] opened 2019-05-20 16:00 UTC
I am trying to rename the main file of a component.

I am getting this error:
```
❯ bit add --main index.ts --id tree-viewer
error: file or directory "" was not found.
```

(It took me a while to understand that I am at the wrong directory, but the error description is missing!)

```
❯ bit tag tree-viewer
error: main file src/ui/file-explorer/tree-viewer/index.js was removed from bit.gui/tree-viewer@0.0.1.
please use "bit remove" to delete the component or "bit add" with "--main" and "--id" flags to add a new mainFile
```

so, I tried to run this command:
```
❯ bit add --main index.ts --id tree-viewer
error: file or directory "" was not found.
```

bit add 

## Expected Behavior
```error: file or directory "index.ts" was not found.```

## Actual Behavior
missing target filename:
```error: file or directory "" was not found.```

## Steps to Reproduce the Problem

  1. track component
  1. tag and export
  1. rename main file
  1. run ```bit add --main``` for this file

## Specifications

  - Bit version: 14.1.0
  - Node version: 6.7.0
  - npm / yarn version: yarn 1.15.2
  - Platform: macos

**Comment by davidfirst** [comment] 2019-05-20 19:25
Thanks @KutnerBitsrc for reporting this.
It's actually easier to reproduce, just run `bit add -i whatever` and you'll get the same error.
The problem with the command you were running is that the path argument is missing. You should have probably run `bit add index.ts --main index.ts --id tree-viewer`.
Of course, the error you got doesn't help much. That's because for some reason the path argument is optional. In the commit above it has been fixed to be required.

**Comment by davidfirst** [comment] 2019-05-20 20:35
After rethinking, I'm not sure what I said is correct. Maybe we do want to support optional `path` argument to only change the main file or to add tests files to an existing id.
@GiladShoham , @itaymendel what do you think?

If we do support `bit add` without `path` argument, the current error message we have for running just `bit add` needs to be improved.
```
> bit add
please specify a component ID to add test files to an existing component.
example: bit add --tests [test_file_path] --id [component_id]
```

**Comment by KutnerBitsrc** [comment] 2019-05-21 09:12
I agree, we need this error message, to **indicate the argument is missing**.

why can we run
```example: bit add --tests app.spec.js --id app```
but not
```example: bit add --main app.js --id app```
?

**Comment by itaymendel** [comment] 2019-05-21 10:19
`bit add` has a different behavior when editing `tests`, `files`, `main` and `excludes`
For example:

```bash
$ touch main.js test.js test2.js
$ bit add main.js --tests test.js --main main.js --id foo  # tracking a mock component
tracking component foo:
added main.js
added test.js

$ bit add --tests test2.js --id foo             # I can simply 'add' a test file
tracking component foo:
added main.js
added test.js
added test2.js

$ bit add --exclude test.js --id foo          # can't exclude a file.
error: file or directory "" was not found.

$ mv main.js main2.js
$ bit add --main main2.js --id foo              # can't modify the main file
error: file or directory "" was not found.

$ touch new.js
$ bit add new.js --id foo                           # can simply add a new tracked file to a component
tracking component foo:
...
```

I see two main issues:

### Exlucde a tracked file

Right now it happens implicitly. When Bit no longer finds the file, it excludes the file from the component. However, if the user wants to explicit remove a file, Bit should allow it.

```sh
$ bit add --exclude [full path to excluded file] --id foo
...
```

### Change the main file

The preferred approach is to allow setting a `main` without explicitly tracking the new file.

```sh
$ bit add --main main2.js --id foo
```

However, given that Bit wants the file to be tracked in order to be defined as a `main`, the output should at least tell how to do it properly. For example - 

```sh
$ bit add --main main2.js --id foo
warning: main2.js is not tracked by foo. please run 'bit add main2.js --main main2.js --id foo' to set it as the main file.
```

**Comment by KutnerBitsrc** [comment] 2019-05-23 08:48
wow quickly fixed! thanks @davidfirst

**Comment by GiladShoham** [comment] 2019-05-23 13:13
@KutnerBitsrc @itaymendel @davidfirst I don't see a reason why this syntax won't work
`bit add --main main2.js --id foo`
we should start by internally transform this always to
`bit add main2.js --main main2.js --id foo`
No reason why the user will need to do this.
@davidfirst I don't think we should make the path required.
We should allow adding tests and change the main without the path.
We just need to fix the error in case the path was empty.

**Comment by davidfirst** [comment] 2019-05-24 19:22
@GiladShoham , yes, that what I realized and started to implement.
However, the implementation is more complicated than it seems.
1. if the flag `--override` was not used, Bit only adds files to the existing ones. So, ` bit add --exclude my-file.js` won't work.
2. adding the files when they are not there as you mentioned, is also not simple. some files might be tests and acting like they were part of the command, will mark them as `test: false`.

Obviously, it's possible to overcome these issues, but it needs some refactoring first. I started it in this PR: https://github.com/teambit/bit/pull/1652.

**Comment by davidfirst** [comment] 2019-06-15 02:31
I merged some refactoring (https://github.com/teambit/bit/pull/1652) to facilitate fixing this issue. 
However, before continue working on it, we need to decide whether the options to change main-file, exclude some files, add a test-file should be as part of `add` command, or maybe as @GiladShoham  suggested something like `edit` command.

**Comment by GiladShoham** [comment] 2019-06-23 09:40
@itaymendel @davidfirst Let's open a dedicated issue to discuss add vs edit or something similar.

**Closed** 2021-03-07 12:46 UTC
