### ISSUE TITLE
incorrect link files in capsule 

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1771] opened 2019-07-01 13:09 UTC
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

  1. git clone https://github.com/valor-software/ngx-bootstrap.git 
  1. npm i
  1. bit init
  1. git clone https://github.com/teambit/bit.envs.git
  1. move to qbllr/ng-packgr branch in bit.envs
  1. bit install 
  1. set the following in ngx-bootstrap:
```js
"bit": {
    "env": {
      "compiler": {
        "mets" :{ 
          "options": {
            "file": "/Users/giladshoham/dev/bit/bitenvs/dist/components/compilers/ng-packagr/ng-packagr.js"
          }
        }
      }
    },
    "resolveModules": {
      "aliases": {
        "ngx-bootstrap": "src/"
      }
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm"
  } 
```
use this .bitmap
```js
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "accordion": {
        "files": [
            {
                "relativePath": "src/accordion/accordion-group.component.html",
                "test": false,
                "name": "accordion-group.component.html"
            },
            {
                "relativePath": "src/accordion/accordion-group.component.ts",
                "test": false,
                "name": "accordion-group.component.ts"
            },
            {
                "relativePath": "src/accordion/accordion.component.ts",
                "test": false,
                "name": "accordion.component.ts"
            },
            {
                "relativePath": "src/accordion/accordion.config.ts",
                "test": false,
                "name": "accordion.config.ts"
            },
            {
                "relativePath": "src/accordion/accordion.module.ts",
                "test": false,
                "name": "accordion.module.ts"
            },
            {
                "relativePath": "src/accordion/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "src/accordion/package.json",
                "test": false,
                "name": "package.json"
            },
            {
                "relativePath": "src/accordion/public_api.ts",
                "test": false,
                "name": "public_api.ts"
            }
        ],
        "mainFile": "src/accordion/public_api.ts",
        "trackDir": "src/accordion",
        "origin": "AUTHORED",
        "exported": false
    },
    "collapse": {
        "files": [
            {
                "relativePath": "src/collapse/collapse-animations.ts",
                "test": false,
                "name": "collapse-animations.ts"
            },
            {
                "relativePath": "src/collapse/collapse.directive.ts",
                "test": false,
                "name": "collapse.directive.ts"
            },
            {
                "relativePath": "src/collapse/collapse.module.ts",
                "test": false,
                "name": "collapse.module.ts"
            },
            {
                "relativePath": "src/collapse/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "src/collapse/package.json",
                "test": false,
                "name": "package.json"
            },
            {
                "relativePath": "src/collapse/public_api.ts",
                "test": false,
                "name": "public_api.ts"
            }
        ],
        "mainFile": "src/collapse/public_api.ts",
        "trackDir": "src/collapse",
        "origin": "AUTHORED",
        "exported": false
    },
    "utils": {
        "files": [
            {
                "relativePath": "src/utils/decorators.ts",
                "test": false,
                "name": "decorators.ts"
            },
            {
                "relativePath": "src/utils/facade/browser.ts",
                "test": false,
                "name": "browser.ts"
            },
            {
                "relativePath": "src/utils/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "src/utils/linked-list.class.ts",
                "test": false,
                "name": "linked-list.class.ts"
            },
            {
                "relativePath": "src/utils/package.json",
                "test": false,
                "name": "package.json"
            },
            {
                "relativePath": "src/utils/public_api.ts",
                "test": false,
                "name": "public_api.ts"
            },
            {
                "relativePath": "src/utils/theme-provider.ts",
                "test": false,
                "name": "theme-provider.ts"
            },
            {
                "relativePath": "src/utils/trigger.class.ts",
                "test": false,
                "name": "trigger.class.ts"
            },
            {
                "relativePath": "src/utils/triggers.ts",
                "test": false,
                "name": "triggers.ts"
            },
            {
                "relativePath": "src/utils/utils.class.ts",
                "test": false,
                "name": "utils.class.ts"
            },
            {
                "relativePath": "src/utils/warn-once.ts",
                "test": false,
                "name": "warn-once.ts"
            }
        ],
        "mainFile": "src/utils/public_api.ts",
        "trackDir": "src/utils",
        "origin": "AUTHORED",
        "exported": false
    },
    "version": "14.1.4-dev.5"
}
```
  1. bit build accordion
  1. look into the capsule in `node_modules/ngx-bootstrap/collapse/index.ts`

This file has 3 problems:
1. it refers to `@bit/collapse` but this doesn't exist (I would expect bit to create it and symlink to `[capsule-root]/.dependencies/collapse`
2. it refers to a file instead of the package root.
3. it has the .ts in the from statement (a .ts is never required in from) (this should be gone after solving issue num 2, but we should address this as well for other cases when we do refer to ts files.
 
### Expected Behavior

I would expect index.ts to have
```js
import { CollapseModule } from '@bit/collapse';
export { CollapseModule };
```
And to actually have a symlink in '@bit/collapse' to `[capsule-root]/.dependencies/collapse`
### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

  - Bit version: master
  - Bit compiler (include version): custom angular compiler

**Comment by davidfirst** [comment] 2019-07-01 20:32
I was able to reproduce these issues

> This file has 3 problems:
> 1. it refers to @bit/collapse but this doesn't exist (I would expect bit to create it and symlink to [capsule-root]/.dependencies/collapse
> 2. it refers to a file instead of the package root.
> 3. it has the .ts in the from statement (a .ts is never required in from) (this should be gone after solving issue num 2, but we should address this as well for other cases when we do refer to ts files.


1. When creating the capsule using `bit isolate accordion --use-capsule -d your-directory`, you can see how the symlinks are generated correctly. 
The problem here is with the `ng-packagr` compiler. It runs `const val = await capsule.exec('npm i tslib')` after creating the capsule. As a result, npm deletes all `node_modules/@bit` content.
2. That is actually the expected behavior. When a component requires a file inside another component, it generates the `require` statement with the package-name + the internal file path. 
Here, in the original project, `accordion` requires `collapse`, which is a directory, in that directory, there is an `index.ts` file, so according to node require logic, it's ended up require `collapse/index.ts`. The main file of collapse, however, is `public_api.ts` and not `index.ts`. 
To get the generated link file to be only the package name, I suggest re-creating the collapse component with `index.ts` as the main file.
3. This is indeed a bug and it has been fixed in the following PR: https://github.com/teambit/bit/pull/1773

**Comment by qballer** [comment] 2019-07-02 13:40
I've tried creating the capsule with bit isolate and it creates a package.json with nulls. 
```
"dependencies": {
    "@angular/common": "^8.0.3",
    "@angular/core": "^8.0.3",
    "@bit/collapse": null,
    "@bit/utils": null
  },
```
Also another weird thing I also see `@bit/accordion` in node_modules. This should be the capsule of the accordion, so I'm unsure why accordion appears in the node_modules.

**Comment by davidfirst** [comment] 2019-07-02 15:18
> I've tried creating the capsule with bit isolate and it creates a package.json with nulls. I've used the bit -w option in order to write the dependencies to the package.json.

Don't use `-w` option with the capsule. This PR https://github.com/teambit/bit/pull/1726 once merged, will take care of that automatically. (I know it's not documented but using the capsule with `bit isolate` is more of a POC to easily create a capsule).

>  Also another weird thing I also see @bit/accordion in node_modules. This should be the capsule of the accordion, so I'm unsure why accordion appears in the node_modules.

Yeah, I noticed that, it has been done originally when the root capsule wasn't the root component. (before the structure change). However, I don't think it's a bad thing, imagine one of the dependencies requires this component. (It'll be cyclic but it'll work for most cases).

> I don't see that installing "tslib" actually removes the node_modules @GiladShoham claims it does, so this may mean different behaviors on different machines.

It probably depends on the NPM version. I tried 5.x and 6.9.x and it did delete. What version are you using for NPM and node?

**Comment by qballer** [comment] 2019-07-02 15:34
NPM version is 6.9.0.
Will try with out w and come back

**Comment by davidfirst** [comment] 2019-07-03 03:01
An update.
Turns out that the symlink of node_modules/@bit/accordion to the capsule root was the cause of packages disappear from node_modules.
It has been fixed on this PR https://github.com/teambit/bit/pull/1777.

**Closed** 2019-07-04 17:09 UTC
Labels: type/bug
