### ISSUE TITLE
tag -all foundComponent.listVersions is not a function

### ISSUE THREAD

**Issue by Plow74** [teambit/bit#769] opened 2018-02-13 19:07 UTC
## Expected Behavior
items are tagged correct and can be exported

## Actual Behavior
foundComponent.listVersions is not a function

## Steps to Reproduce the Problem

  1. renamed scss file to css
  2. added components using bit add src\components\*
  3. run tag --all and get the above error
 4. therefore nothing to export...

## Specifications

  - Version: 0.12.5
  - Platform: Windows

EDIT - also noticed the css file is not included in the dist directory when using `bit build`

EDIT - looking closer, I see the .bitmap file looks a bit confused...

`
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "**plow74.ulp/components/ulp-notification-status-indicator@0.0.2**": {
        "files": [
            {
                "relativePath": "src/components/ulp-notification-status-indicator/index.js",
                "test": false,
                "name": "index.js"
            },
            {
                "relativePath": "src/components/ulp-notification-status-indicator/ulp-notification-status-indicator.js",
                "test": false,
                "name": "ulp-notification-status-indicator.js"
            }
        ],
        "mainFile": "src/components/ulp-notification-status-indicator/index.js",
        "origin": "AUTHORED"
    },
    "**components/ulp-notification-status-indicator**": {
        "files": [
            {
                "relativePath": "src/components/ulp-notification-status-indicator/index.js",
                "test": false,
                "name": "index.js"
            },
            {
                "relativePath": "src/components/ulp-notification-status-indicator/style.css",
                "test": false,
                "name": "style.css"
            },
            {
                "relativePath": "src/components/ulp-notification-status-indicator/ulp-notification-status-indicator.js",
                "test": false,
                "name": "ulp-notification-status-indicator.js"
            }
        ],
        "mainFile": "src/components/ulp-notification-status-indicator/style.css",
        "origin": "AUTHORED"
    },
    "version": "0.12.5"
}
`

**Comment by GiladShoham** [comment] 2018-02-14 16:39
Hi @Plow74 
Thanks for reporting this.

We are checking this to understand what caused this problem.
It will be very helpful if you can send me the whole working directory since this is probably a problem with bit objects.
you can send it privately to my email gilad@bitsrc.io or share it here if there is nothing sensitive.
meantime we will keep investigating this issue.

**Comment by GiladShoham** [comment] 2018-02-15 12:41
Update:
We were able to reproduce the bug and understand the root cause.
It's indeed a problem with duplications in the .bitmap file, happened during the second add command (after the rename)
We are working to solve it and will update once it solved.

**Comment by GiladShoham** [comment] 2018-02-18 16:22
@Plow74 
The bug has been resolved as part of https://github.com/teambit/bit/pull/781
It's already merged and will be part of the next version in few days.

**Comment by GiladShoham** [comment] 2018-02-28 09:14
Solved in 0.12.6

**Closed by GiladShoham** 2018-02-28 09:14 UTC
Labels: area/build, area/tag, type/bug
