### ISSUE TITLE
Yarn + failed to generate a symlink + missing package.json

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8171] opened 2023-11-20 14:06 UTC
### Describe the bug

Custom react env doesn't generate a `package.json` file which makes `yarn` failed with `failed to generate a symlink` error. Can't build or start the project

```
failed to generate a symlink.
Symlink from: /Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/@hexa-react-web/envs.react-component/package.json, to: /Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/@hexa-react-web/envs.react-component/package.json was failed.
Please use "--log=trace" flag to get more info about the error.
Original error: Error: ENOENT: no such file or directory, link '/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/@hexa-react-web/envs.react-component/package.json' -> '/Users/giulianomini/Projects/ABInDev/hexa-react-web/node_modules/@hexa-react-web/envs.react-component/package.json'
```

![Screenshot 2023-11-16 at 17 20 48](https://github.com/teambit/bit/assets/144352874/94f97b9a-1afe-4fb1-845e-26f47f6cb70a)

![Screenshot 2023-11-16 at 17 21 09](https://github.com/teambit/bit/assets/144352874/2a74b354-e555-4d59-b63d-e5c2aad21de5)

Note: can't switch to `pnpm` due to https://github.com/pnpm/pnpm/issues/5970

### Steps to Reproduce

1. Create a custom env
1. Use `yarn`
1. Try to build or start the project, doesn't generate the `package.json` and link fails

### Expected Behavior

Envs should create a `package.json`

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Workspace type: (harmony/legacy)
- Node version:
- npm / yarn version:
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment] 2023-11-20 17:45
hi @giuliano-abinbev , which version of Bit you are using and is your OS?
i am unable to reproduce the error you get (not being unable to generate the `package.json`)

also, in which workflow you get this error? which command do you run?

**Comment by zkochan** [comment] 2023-11-27 17:12
That pnpm issue should be fixed in the next nightly Bit version.

**Comment by itaymendel** [comment] 2023-12-12 18:54
the underline pnpm issue was resolved. i am closing the issue.

**Closed by itaymendel** 2023-12-12 18:54 UTC
Labels: type/bug
