### ISSUE TITLE
Unable to use https://www.npmjs.com/package/rmwc "Should not import the named export 'version' (reexported as 'version') from default-exporting module"

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5278] opened 2022-01-14 17:19 UTC
### Describe the bug
Upon installing this ui library package I am no longer able to 'start' my bit harmony project

```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+rmwc@6.1.4_react-dom@17.0.2+react@17.0.2/node_modules/rmwc/next/index.js 1:0-50
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ ./node_modules/@frnt/base-ui.button/dist/button.js 22:31-46
 @ ./node_modules/@frnt/base-ui.button/dist/button.docs.mdx 19:0-34 31:14-20
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.harmony/node/__overview-1642180303613.js 6:13-140
```

### Steps to Reproduce
1. bit install rmwc tslib
1. bit compile
1. bit start
1. import rmwc from 'rmwc'

### Expected Behavior
App should compile and run, this library works perfectly fine in a normal react project.

### Screenshots, exceptions and logs
```
C:\Users\test\Documents\Projects\FRNT\ui-elements>bit start
Compiling...


You can now view 'ui-elements' components in the browser.
Bit server is running on http://localhost:3000
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
    at HarmonyExportImportedSpecifierDependency.getLinkingErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyImportDependency.js:190:7)
    at HarmonyExportImportedSpecifierDependency._getErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:760:21)
    at HarmonyExportImportedSpecifierDependency.getErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:748:16)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2595:22)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2204:10
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:376:11
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:355:18
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.finish (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2196:28)

ModuleDependencyError: Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2600:21)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2204:10
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:376:11
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:355:18
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.finish (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2196:28)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compiler.js:1104:19
ERROR in ./node_modules/.pnpm/registry.npmjs.org+rmwc@6.1.4_react-dom@17.0.2+react@17.0.2/node_modules/rmwc/next/index.js 1:0-50
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ ./node_modules/@frnt/base-ui.button/dist/button.js 22:31-46
 @ ./node_modules/@frnt/base-ui.button/dist/button.docs.mdx 19:0-34 31:14-20
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.harmony/node/__overview-1642180303613.js 6:13-140

webpack compiled with 1 error
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
    at HarmonyExportImportedSpecifierDependency.getLinkingErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyImportDependency.js:190:7)
    at HarmonyExportImportedSpecifierDependency._getErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:760:21)
    at HarmonyExportImportedSpecifierDependency.getErrors (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:748:16)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2595:22)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2204:10
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:376:11
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:355:18
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.finish (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2196:28)

ModuleDependencyError: Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2600:21)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2204:10
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:376:11
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:355:18
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:2850:39)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\Hook.js:18:14)
    at Compilation.finish (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:2196:28)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compiler.js:1104:19
    at processTicksAndRejections (internal/process/task_queues.js:75:11)



You can now view 'ui-elements' components in the browser.
Bit server is running on http://localhost:3000
```

### Specifications
Bit version: 0.0.617
Workspace type: (harmony/legacy) harmony
Node version: v14.16.0
npm / yarn version: 6.14.11
Platform: Windows
for harmony workspace

relevant env: react

**Comment by itaymendel** [comment] 2023-05-21 15:34
unable to reproduce on latest versions of Bit. might got resolved somewhere in the past year. closing the issue.

**Closed by itaymendel** 2023-05-21 15:34 UTC
Labels: type/bug
