### ISSUE TITLE
AppVeyor CI 

### ISSUE THREAD

**Issue by ranm8** [teambit/bit#2565] opened 2020-04-08 11:51 UTC
@davidfirst @GiladShoham as we all now AppVeyor is failing for a while now and and I'm worried we would find many regressions in Harmony for windows.
What can we do about it?

**Comment by davidfirst** [comment] 2020-04-08 12:04
@ranm8 , here is the problem.
AppVeyor is extremely slow, it takes 1.5 hours to complete. Also, more often than not, it fails due to timeout. As a result, it's hard to enforce to keep it green in the current state that we push many times a day to the main branch.

> we would find many regressions in Harmony for windows.

I'm sure we'll find many regressions on Windows.  We can fix them now or fix them all once we finish. I'm good with both options. Let us know.

**Comment by ranm8** [comment] 2020-04-08 12:19
I prefer to be in sync with Windows issues early in the development process and not find our how bad the situation is eventually. Can we use Circle instead? How can we pace the CI build time?

**Comment by davidfirst** [comment] 2020-04-08 12:55
Circle had this Beta version of Windows and Gilad registered to it. @GiladShoham , what's the status there?

**Comment by GiladShoham** [comment] 2020-04-08 13:08
There will be probably many issues with harmony on windows. My guess mainly tests mistakes with paths. But not necessarily.
Yes we can configure circle for windows. I think it's also out of beta already.
It require probably a day of work on configuration.
It will also might be a bit expensive since the windows machines are very strong therefore very expensive. With the Linux you can choose the hardware with windows not.
I can't estimate the prices without really running it.
Its also affected by the parallelism.
I'm sure it will eventually technology wise will be much better since circle is much better than appveyor. It will also put everything under one roof which is good and will be more stable and faster.
I really want to do it for a long time.. Just let me know if you want me to try migration to circle, try fix tests with appveyor or keep it to the end.
@ranm8

**Comment by GiladShoham** [comment] 2020-04-19 10:44
fixed by #2599

**Closed by GiladShoham** 2020-04-19 10:44 UTC
Labels: type/bug
