### ISSUE TITLE
Bit not recognizing my components

### ISSUE THREAD

**Issue by alesanchezr** [teambit/bit#1174] opened 2018-08-08 21:44 UTC
## Expected Behavior
When I do "$ bit status" it should show my list of 17 components

## Actual Behavior
When I do "$ bit status" it says that I don't have any components
![screen shot 2018-08-08 at 5 37 40 pm](https://user-images.githubusercontent.com/426452/43865937-0d2f675e-9b32-11e8-92ec-7aaf5b85e23c.png)

## Steps to Reproduce the Problem
The normal steps to export specified on bitsrc whant you create a new scope
bit init, login, add and export.

I can git you access to my workspace because is in the cloud. If email si provided.

## Specifications

  - Bit version:13.0.4
  - Node version:v8.11.1
  - npm / yarn version: 5.6.0
  - Platform:  Ubuntu 14.04.5 LTS (I can give you access to the workspace if you give me your bitsrc email)
  - Bit compiler (include version):  I think i have not configured a compiler, it does not show on bit.json.
  - Bit tester (include version): I don't know.

**Comment by itaymendel** [comment] 2018-08-09 09:10
Hi @alesanchezr , from the screenshot you uploaded I see that after exporting components, the next `bit status` tells you that there's nothing to tag or export. This is the intended behavior.

Similar to Git, the `status` command that there are no differences between your workspace and the objects in the local Scope. You can learn more about it [here](https://docs.bitsrc.io/docs/faq-understanding-bit-status.html#nothing-to-tag-or-export).

If you want to [list all components](https://docs.bitsrc.io/docs/cli-list.html) in the workspace, use `bit list`.

I'm closing the issue as the feature works as intended.

**Closed by itaymendel** 2018-08-09 09:10 UTC
