### ISSUE TITLE
@teambit/wiki.apps.wiki overflow left

### ISSUE THREAD

**Issue by peacetrue** [teambit/bit#6096] opened 2022-07-08 19:02 UTC
![](https://user-images.githubusercontent.com/38878763/178054309-d4423460-b7a5-45ef-b7c8-42110bded39f.png)

![](https://user-images.githubusercontent.com/38878763/178054412-907502ad-614d-4c88-801d-c575c864519a.png)

**Comment by odedre** [comment] 2022-07-10 08:32
@peacetrue I cant reproduce the issue. please add more details (os, browser etc)

**Comment by peacetrue** [comment] 2022-07-10 16:24
<img width="564" alt="image" src="https://user-images.githubusercontent.com/38878763/178152934-80dad6b4-a9a5-46e1-ab92-febdc826809d.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/38878763/178152970-2c904072-d410-45e5-9d84-ba848d3ee248.png">
Version 103.0.5060.114 (Official Build) (x86_64)

<img width="284" alt="image" src="https://user-images.githubusercontent.com/38878763/178153050-c3a0de22-6dc7-41cb-a2be-662c95fe7f0c.png">
Version 15.5 (17613.2.7.1.8)


<img width="666" alt="image" src="https://user-images.githubusercontent.com/38878763/178153231-a5b58cc8-3177-40e9-a11f-24a46578d454.png">
102.0.1 (64-bit)

**Comment by peacetrue** [comment] 2022-07-10 16:27
https://e1vfqrk1.scopes.teambit.cloud/api/teambit.harmony/aspect/~aspect/env-template/compositions/#teambit.wiki/apps/wiki@1.91.3?preview=compositions&WikiBasic

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/38878763/178153288-c2010e35-c5d4-4a02-8135-042a60834e12.png">


<img width="1173" alt="image" src="https://user-images.githubusercontent.com/38878763/178153324-870f59e0-c836-4b39-b22f-03656d7b5aa0.png">

**Comment by itaymendel** [comment] 2023-05-21 15:41
resolved as part of a wiki upgrade. closing the issue.

**Closed by itaymendel** 2023-05-21 15:41 UTC
Labels: type/bug
