### ISSUE TITLE
React Hooks cause component to not render

### ISSUE THREAD

**Issue by AlexanderKaran** [teambit/bit#2709] opened 2020-06-06 06:33 UTC
### Describe the bug

When uploading a functional component with a hook inside of it the example fails to render in Bit UI.

### Steps to Reproduce

1. Create a UI component 
1. Add a useMemo hook for caching a value
1. Upload to bit and get an error 

### Expected Behavior

Component UI should render in a collection without any issues

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

![Screen Shot 2020-06-06 at 2 32 58 pm](https://user-images.githubusercontent.com/47707063/83937823-b4816000-a802-11ea-8811-91bbc5256c96.png)
![Screen Shot 2020-06-06 at 2 33 13 pm](https://user-images.githubusercontent.com/47707063/83937830-b64b2380-a802-11ea-82aa-f61d9ec482cc.png)

### Specifications

- Bit version: 14.7.6
- Node version: 13.11.0
- npm / yarn version: 6.13.7
- Platform: Mac/React
- Bit compiler (include version): bit.envs/compilers/react@1.0.17

**Comment by AlexanderKaran** [comment] 2020-06-07 01:05
I since uploaded a few more components with hooks in them and every single one is throwing the error. Is Bit unable to render components with hooks in them?

**Comment by odedre** [comment] 2020-06-09 14:32
@AlexanderKaran can you add a link to your component?

**Comment by KutnerUri** [comment] 2020-06-09 14:38
It's a known issue, we are investigating.

I'm not sure why this is happening, hooks work in the example code, just not in the dists.

**Comment by Tallyb** [comment] 2020-06-09 15:28
@AlexanderKaran  Make sure you are defining React as peer dependencies: https://docs.bit.dev/docs/react-guidelines#add-react-libraries-as-peer-dependencies-with-relaxed-versions

**Comment by GiladShoham** [comment] 2020-06-14 20:29
@KutnerUri @AlexanderKaran 
Can we close this?

**Comment by KutnerUri** [comment] 2020-06-21 13:39
@GiladShoham the problem still exists, we need to better reproduce it

**Comment by giteden** [comment] 2020-06-21 13:50
Here's another functional-component-with-hooks that does not render on Bit's playground (but works perfectly well when installed in other projects)

[https://bit.dev/eden/test-hooks/bad-jokes-viewer](https://bit.dev/eden/test-hooks/bad-jokes-viewer)

As far as I was able to see, this error doesn't happen when rendering React with TS (in Bit's playground).

**Comment by KutnerUri** [comment] 2020-06-21 17:18
ok I made some tests and still no conclusion.

The same code works in the playground (see [here](https://bit.dev/bit/examples/react-health/effect-hook?example=5eef92ef95d329001958427b)), so I'm thinking something is lost during complication.

* react-ts (typescript) compiler seems to be ok with it. (see [here](https://bit.dev/bit/examples/react-health/effect-hook))
* 'react' (babel) compiler seems to be ok with it. (see [here](https://bit.dev/kutner/temp/react-health/effect-hook))
* even when copy pasting the dists for bad-jokes-viewer to the playground, it seems to work (see [here](https://bit.dev/bit/examples/react-health/effect-hook?example=5eef9612c166fb00191835b7))

Failed leads:
* I thought _async-await_ could cause problems during compilation. After changing to promises, it is still happening. (see [here](https://bit.dev/kutner/temp/bad-jokes-viewer/~code#BadJokesViewer/BadJokesViewer.jsx))

**Comment by manishiitg** [comment] 2020-07-06 02:16
it might be due to react peer dependency issue. 

i fixed the same problem using this

https://docs.bit.dev/docs/react-guidelines#add-react-libraries-as-peer-dependencies-with-relaxed-versions

**Comment by itaymendel** [comment] 2021-03-07 15:34
playground rendering feature was reimplemnted with ability to support data-fetching. this is available in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Closed by itaymendel** 2021-03-07 15:34 UTC
Labels: area/bit.dev, type/bug
