### ISSUE TITLE
error with exports in bit

### ISSUE THREAD

**Issue by cristinallamas** [teambit/bit#1430] opened 2019-02-08 16:29 UTC
I get this error in the bit preview, my file structure is the following

index.js (containing export { default as Select } from './Select'; )
Select.js (being the actual component with export default Select)

## Expected Behavior
no errors

## Actual Behavior
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Steps to Reproduce the Problem

  1. export { default as Select } from './Select';
  1.
  1.

## Specifications

  - Bit version: 14.0.0
  - Node version: v10.8.0
  - npm / yarn version: 1.9.4
  - Platform: osx
  - Bit compiler (include version):  bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

**Comment by GiladShoham** [comment] 2019-02-20 09:47
@cristinallamas Can you share your component/example with me (gilad@bitsrc)?
If no, can you create some mock code which reproduces the problem?

**Comment by aldo-sorbara** [comment] 2019-04-05 14:23
@cristinallamas how are you importing the component ?

1- import Select from ./select ?
2- import { Select } from ./select  ?

**Comment by itaymendel** [comment] 2019-05-16 06:41
Closing the issue due to lack of information on reproducing the problem.
During the last couple of days, we've upgraded the rendering infrastructure and resolved many internal issues. I hope that this specific case has been resolved as well. If it does not, please reopen with at least a link to the errored example.

**Closed by itaymendel** 2019-05-16 06:41 UTC
Labels: area/playground, type/bug
