### ISSUE TITLE
When editing en env, when modifications take effect ?

### ISSUE THREAD

**Issue by antoine-durand** [teambit/bit#6197] opened 2022-07-26 17:47 UTC
What need to be done after any modification in a custom env code to take effect ?

bit built 'my-env' ? 
bit tag, ... ?

my need is to be able to build a component with the env after each env modification to test it, 
but bit seems to use an old version of the env until... **_something_** is done ?

**Comment by jonatankBIT** [comment] 2022-07-27 06:16
Until you tag it. Envs are components too :)

**Comment by antoineDemiurge** [comment] 2022-07-27 08:27
Thank you, It doesn't seem obvious to me.
Because when you edit a component which is a dependecy of another one in your workspace, modifications are used immediately in bit UI (Fortunately for parent component too).
but for env you need to tag it, so when you try (hard) to make an env works as intended, it may end up with the v 0.0.872 !
joking aside, is there any way to test an env quickly ?

**Comment by jonatankBIT** [comment] 2022-07-27 08:47
All good. 
I don't know what you mean with test... If you mean to try it you can assign it to a component:

```bit env set <component-pattern> <env>`

Where <comoponent-pattern> could be the id thrown by `bit list` (aka, with the `myOrg.myScope/myComponent`)

Or, if you want to peek on an env, you can run:

```
bit env get <my_env>
```
Lastly, if you want to try and modify an env, you can run `bit fork` and perform the modifications you want:
For example, forking `teambit.react/react` env:
```
bit fork @teambit.react/react my-react-env
```

Hope that helps

**Comment by antoineDemiurge** [comment] 2022-07-27 09:19
Ok sorry, here is some context:
I've done this:

```
bit create react-env my-react-env
bit env set test-component xxxxxxx.default/my-react-env
bit build
```

but now when I change anything in _my-react-env_ and then I would like to build _test-component_ to check if _my-react-env_ works. But the changes* made in _my-react-env_ are not used during  _test-component_ build, event after I taged _my-react-env_.

*(Let's say I just add a webpack's config raw output to the console, just to start to see what is the default config and check _my-react-env_ code is run)

**Comment by antoineDemiurge** [comment] 2022-07-27 14:04
whatever I do :

1. tag the custom react env _my-react-env_
2. even export it
3. set custom react env _my-react-env_ to a new react component  _test-component-2_
4. set back _teambit.react/react_ env to react component _test-component_  and then set my custom env _my-react-env_ again

bit continue to use the first version of _my-react-env_ and behave like new modifications in _my-react-env_ don't exist.
(despite having the right version of _my-react-env_ showing up in `bit show test-component`)

**Comment by itaymendel** [comment] 2023-03-06 11:58
you must `bit compile` to have env changes take affect in a worksacpe. or use `bit watch` to get it for free.

**Closed by itaymendel** 2023-03-06 11:58 UTC
Labels: type/help wanted
