### ISSUE TITLE
bit should execute when in windows 'admin' mode

### ISSUE THREAD

**Issue by donkindred** [teambit/bit#2390] opened 2020-02-24 20:52 UTC
### Description

Whenever I run a bit command with admin cmd, the command does nothing. I've tried a dozen commands, but there's no feedback on any of them. It just goes to the next line. I've been unable to make any aspect of the program work with both versions listed below. I've tried bit-bin-win.exe and npm install. Users Tally Barak and Gilad Shoham on Slack attempted to help, but they directed me here in the end. Any ideas?

### Specifications

- Bit version: 14.7.6 & 14.7.4
- Node version: 8.11.3
- npm / yarn version: 6.9.1
- Platform: Windows 10

**Comment by KutnerUri** [comment] 2020-03-30 16:16
I think I had something similar while running as `sudo` in Linux. Maybe there are not global packages in admin mode?
I worked around it by installing bit in the local project, and running it directly:
```
❯ npm -i bit-bin
...
❯ ./node_modules/bit-bin/bin/bit.js -v
14.7.6
```

**Comment by davidfirst** [comment] 2020-04-10 16:18
@donkindred , I'm unable to reproduce it.
On my Windows machine, I searched for "cmd" and open with "run as administrator", then I typed "bit" and got the help as expected.

Here are the details about my Win10 version. Please let me know if you have an idea how could I reproduce it.

![Uploading Screen Shot 2020-04-10 at 12.16.22 PM.png…]()

**Comment by GiladShoham** [comment] 2020-04-12 11:55
can you try run `which bit` or `where bit`?
(you might need to install those tools on windows)
then looking at this location to see what is going on there.
(it's better to install with npm at the moment for investigating this)

**Comment by itaymendel** [comment] 2021-03-07 13:59
unable to reproduce. closing issue.

**Closed by itaymendel** 2021-03-07 13:59 UTC
Labels: type/help wanted
