### ISSUE TITLE
"bit status" fails with "Invalid Version: .DS_Store"

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#1941] opened 2019-08-20 15:51 UTC
### Describe the bug

I was trying bit on my new project. I initialised bit in a workspace, created `bit.json` file and added some components with some namespaces, tagged and exported them(They appeared at bit.dev and everything is ok). After all these actions, I typed `bit status` and received an error: `Invalid Version: .DS_Store` (I'm using Mac). Now every command results in this error. 

I only found this issue [here](https://github.com/GitbookIO/gitbook-cli/issues/8), that may be related. I tried to remove `.DS_Store` from my project folder and checked, if there are any in my `/usr/local/lib/node_modules/bit-bin/` directory(but didn't find them). I also tried to find similar code as in the issue above to workaround the problem, but failed.

### Steps to Reproduce
Don't know how to reproduce this, `bit init --reset` command also fails in this project, but everything works fine in a new one.
 
### Expected Behavior

I expect no errors, when using `bit status`

### Specifications

- Bit version: 14.2.4
- Node version: v10.16.0
- npm / yarn version: 6.10.3
- Platform: macOs Mojave 10.14.5 (18F132)
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.0.6
- Bit tester (include version): -

**Comment by GiladShoham** [comment] 2019-08-21 08:24
@DeyLak 
Hi,
That's a weird issue I never saw.
Looks like it's some conflict between bit and the os.
Do you have any idea how can I reproduce it?
Can you check if your .bitmap file contains this file under one of the components?
Maybe if there is nothing sensitive in this folder you can tar and send it over?
If there is sensitive info there, maybe you can just delete all the actual content and only send the skeleton of the folder?
In general, I believe that if you will delete the .git/bit folder / .bit folder from the root, and re-init bit, it will be fine. (this, of course, will delete all your components which were tagged but never exported).

**Comment by DeyLak** [comment] 2019-08-21 09:00
@GiladShoham thanks, deleting .git/bit folder manually helped. I created copy of my folder, deleted `.git` folder, moved `.git/bit` to `.bit` and deleted a lot of files, but the error is still there. I think, that the problem is in `.bit` folder itself.
[ds_store_bug.tar.gz](https://github.com/teambit/bit/files/3524418/ds_store_bug.tar.gz)

I didn't find any mentions of `.DS_Store` in my `.bitmap` file.

**Comment by GiladShoham** [comment] 2019-08-21 10:11
The problematic file is in this path:
`.bit/components/compilers/react-typescript/bit.envs/.DS_Store`
This is mac os file created on each folder you access using the built-in finder app.
Removing this file will fix the workspace.
Open this folder again with finder will re-create this file and corrupt the workspace again.
I'll check what we can do about it.
Thanks for reporting this.

**Comment by GiladShoham** [comment] 2019-08-21 10:46
I made a PR to fix the issue from bit's side. so it won't happen even if the ds_store file exists.
It will be merged in about an hour and will be part of the next release.

**Comment by DeyLak** [comment] 2019-08-21 11:16
Thanks for the quick response and help!

**Comment by DeyLak** [comment] 2019-08-21 11:23
By the way, there are similar purpose files on windows: `thumbs.db` and `desktop.ini` May be, they also could cause problems.

**Comment by GiladShoham** [comment] 2019-08-21 12:14
> By the way, there are similar purpose files on windows: thumbs.db and desktop.ini May be, they also could cause problems.


Thanks, I'll check it.

**Closed** 2019-08-21 12:14 UTC
Labels: type/bug
