### ISSUE TITLE
Bit giving conflicting information about component 

### ISSUE THREAD

**Issue by Mujaddadi** [teambit/bit#2315] opened 2020-02-10 09:28 UTC
### Describe the bug

I imported a component to edit it. When I finished editing the component, I exported it successfully. When I see the bit status, it still say to export that particular component. 

```        staged components
        (use "bit export <remote_scope> to push these components to a remote scope")

     > ui/modal. versions: 1.0.1 ... ok

```
When I do bit export, it says nothing to export 

`- exporting component
nothing to export
`

And this issue happens quite often. I checked the names and there is no conflicts in name

### Specifications

- Bit version: 14.6.0
- Node version: 12.13.1
- npm version:  6.12,1
- Platform: Windows 10

**Comment by Mujaddadi** [comment] 2020-02-10 09:40
I also did `bit clear-cache` and `bit remove 'component'` but it didn't solve the issue.

**Comment by Mujaddadi** [comment] 2020-02-10 10:31
Ok so I solved the issue with 
```
 bit untag --all
error: component "dc20.lib/ui/modal@1.0.1" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)
```
Although it says component was not found, but it somehow solved the problem.  I am not sure its because I was not using this flag `--set-current-scope'` when I was exporting. Testing it now

**Comment by Mujaddadi** [comment] 2020-02-10 10:43
So yeah even setting the `--set-current-scope` with bit export didn't remove the component from staging.

**Comment by GiladShoham** [comment] 2020-02-10 13:42
@Mujaddadi Thanks for reporting this.
We will look into it.
In general, when you export to another collection which is not the original one, it's by design to keep it as staged, that's because you might want to export it back to the original one.
The `--set-current-scope` should do the trick and make it not staged.

**Comment by itaymendel** [comment] 2021-03-07 14:41
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Closed by itaymendel** 2021-03-07 14:41 UTC
Labels: type/bug
