### ISSUE TITLE
Bit eject shows failure due to updates that are not exist

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#5766] opened 2022-05-02 13:15 UTC
### Describe the bug
`bit eject` fails on having modified components, but there are no such components in `bit status`

### Steps to Reproduce
1. `bit status` -> no changes
1. `bit diff component` -> no changes
1. `bit eject` -> fail

```
failed to eject the following components
stopped the eject process for the following components because they have local changes.
```

### Expected Behavior
It should not fail on modified components when there are no changes.

### Screenshots, exceptions and logs
its the only one difference in `calculateHash` functions and I could not find where it comes from, 
both versions are not existed anywhere in the project.

```
packageJson.devDeps "@types/jest": "27.0.3",
workspace.policy.peerDeps "@types/jest": ">=26.0.0",
```

`Consumer.isComponentModified`

```js
componentFromFileSystem._isModified = componentFromModel.calculateHash().hash !== version.calculateHash().hash;
```

![](https://user-images.githubusercontent.com/3938372/166238521-47993736-a7bb-4803-a39d-380e538f534f.png)

`bit show` and `npm ls` 
| package | version |
|---------|---------|
|  custom-react  |  ^26.0.0       |
|     custom-node    |    ^26.0.0     |
|     teambit.envs/envs    |     ^26.0.0    |
| teambit.harmony/aspect  |  ^26.0.0       |
|    @teambit/harmony-ui-app     |    26.0.20     |
|    teambit/yarn     |     26.0.20    |

### Specifications
* Bit version: 0.0.725
* Workspace type: (harmony/legacy) harmony
* Node version: 16
* npm / yarn version: yarn 1 latest
* Platform: osx M1

**Comment by itaymendel** [comment] 2023-03-19 22:09
unable to reproduce... closing the issue.

**Closed by itaymendel** 2023-03-19 22:09 UTC
Labels: type/bug
