### ISSUE TITLE
Build components with babel with alias

### ISSUE THREAD

**Issue by northkode** [teambit/bit#1331] opened 2018-11-14 05:10 UTC
## Expected Behavior
Proper importing on babel compiled components when using alias

## Actual Behavior
errors out when installing component via npm, it keeps the alias in the require('@pwa/core/Cache') commands and fails to build in project

## Steps to Reproduce the Problem

  1. add an alias in your bit.json
  1. in your components use that alias for the import `import Cache from '@pwa/core/Cache'`
  1. run `bit build` with the babel compiler
  1. push the built files up with a new tag
  1. npm install component and try and require it
  1. you'll get an error  Error: Can't resolve '@pwa/core/Cache' because in dependencies they are littered with require('@pwa/core/Cache') instead of the real npm path

## Specifications

  - Bit version: 13.0.4
  - Node version: 10.9
  - npm / yarn version: 6.4.1
  - Platform: mac
  - Bit compiler (include version): babel
  - Bit tester (include version):non

I  was able to get my stuff to work by adding an alias in my local webpack config
'@pwa': '@bit/{owner}.{namespace}.components.pwa'.

But this really should be part of the compiler or the bit alias resolving command and change those @pwa to relative paths in the npm package of bit

**Comment by itaymendel** [comment] 2018-11-14 10:58
hi @northkode the problem is that the babel compiler environment comes with its own set of configs.
This means that it is not aware of the aliases configured in `bit.json`. What you need to do is to change the compiler's configs to fit your project. You can look at the steps in this [SO question](https://stackoverflow.com/questions/52311627/bitsrc-typescript-transpiler-creates-references-to-module-js-map/53277195#53277195).

We are working on adding APIs to allow passing of configs to an environment from the project itself, so this should be properly resolved in the near future.

**Closed by itaymendel** 2018-11-14 10:58 UTC

**Comment by northkode** [comment] 2018-11-14 15:11
@itaymendel  I see what your saying but i'm not sure that is the issues.

The babel compiler compiled the code perfectly and pushed it up to my components just fine. 

*Small snippet of babel compiled code *
```
var _Utils = require("@pwa/utils/Utils");
var _StateManager = require("@pwa/managers/StateManager");
var _MobileEvents = require("@pwa/events/MobileEvents");
var _EventDispatcher = require("@pwa/events/EventDispatcher");
var PWAApp = function () {
    function PWAApp() {
        _classCallCheck(this, PWAApp);
    }
```
The above snippet has been properly compiled into es5 with all required classes being compiled into es5 as well. 

But you'll notice that it left the alias in the code instead of dynamically moving those to relative paths. So when I npm install that component into another project I have to add a custom alias into that projects webpack config for the component to require its dependencies properly
