### ISSUE TITLE
bit import ... --merge not updating component version in .bitmap

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1971] opened 2019-09-03 09:03 UTC
### Describe the bug

I exported a new version of a component, and import it in a project that has an older version of this component.
I make changes locally, `bit import <component id> --merge` didn't update the version in bitmap

### Steps to Reproduce
1. `bit import joshk.cashmere-t1/button@2.1.0`                                                                                          
1. change something inside the component
1. `bit import joshk.cashmere-t1/button --merge` (will bring v2.1.1)
1. look at bitmap - the version is still 2.1.0

### Specifications

- Bit version: 14.2.6-dev.2
- Node version: v10.16.0
- npm version: 6.9.0
- Platform: macOS

**Comment by davidfirst** [comment] 2019-09-03 21:56
I think there is a confusion here between `checkout` and `merge`.
`bit merge` or `bit import --merge` don't change the version. They only merge the changes from the specified version into the current .bitmap version.
`bit checkout --<any-merge-flag>` does what you're looking for. It checks out to the specified version and merges the local changes into that version.

**Comment by GiladShoham** [comment] 2019-09-04 10:44
@davidfirst Thanks.
Few notes:
1. I tried the same flow with some other arbitrary component and it did change the version. so at least we have an inconsistency here.
2. when I have some component version and I import the same component explicitly (if I don't have any modification) it will update the version. I don't see why when using merge it will behave differently.
3. When I do have changes it asks me to use override or merge. If we only fetch the objects why do we need either of them? (like we don't need it when using `bit import` without component id. 
4. importing a specific component is like fetch and checkout to imported version / latest. that's the behavior in any other flow.
@itaymendel would love to hear your opinion here as well.

**Comment by davidfirst** [comment] 2019-09-04 13:53
You're right, my bad. `bit import --merge` fetches the new version and checkout to that version.

I tried the example above and it did change the .bitmap to the new version `2.1.2`.
So, I'm unsure how to reproduce it. I tried with/without changing the code ov 2.1.0. Tried also to bring 2.1.1 instead of latest 2.1.1. Tried to `git checkout` to the code of yesterday. Same results. It did update the `.bitmap` file.

**Comment by GiladShoham** [comment] 2019-09-05 10:50
I didn't manage to reproduce it today as well.
Not sure what has been changed.
(only that @JoshK2 export a new version). Maybe it happens only when the 2.1.1 was the latest.

@JoshK2 closing for now, please re-open if you see it again.

**Comment by JGJP** [comment] 2020-06-16 03:24
I'm experiencing this same issue. Actually `bit import --merge theirs` doesn't seem to do anything besides reorder the bitmap file per #2503

Bit version: 4.7.6
Node version: 12.16.2
npm / yarn version: 1.22.4
Platform: macOS 10.15.5

**Comment by GiladShoham** [comment] 2020-06-16 20:57
@JGJP can you elaborate on the full workflow you did and what happens / what you expected to happen?

**Comment by JGJP** [comment] 2020-06-19 01:32
- `bit import`
- one of the component is marked as updated, because there's a newer version on the server
- `bit import --merge`
- it now says all components are up to date
- there are no changes to the components or .bitmap file
- `bit status` shows that the component in question is not updated

**Comment by GiladShoham** [comment] 2020-06-22 11:31
@davidfirst Please take a look at this

**Comment by itaymendel** [comment] 2021-03-07 12:27
resolved as part of v15
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Closed by itaymendel** 2021-03-07 12:27 UTC
Labels: area/import, priority/critical, type/bug
