### ISSUE TITLE
bit link uses git command

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#3984] opened 2021-03-24 17:06 UTC
### Describe the bug
`bit link` command produces `/bin/sh: git: not found` errors.

### Steps to Reproduce
1. Add `RUN bit link` to Dockerfile
1. Start docker build

### Expected Behavior
`bit link` doesn't use git or have configurable alternative to avoid installing git into Docker.

### Screenshots, exceptions and logs
```
RUN bit link:
#16 0.738 /bin/sh: git: not found
#16 0.744 /bin/sh: git: not found
#16 0.832 /bin/sh: git: not found
#16 0.838 Warning: running bit as root might cause permission issues later
#16 0.877 /bin/sh: git: not found
#16 0.880 /bin/sh: git: not found
```

### Specifications
* Platform: Docker Image `node:12-alpine`
* Bit version: 0.0.331
* Node version: v12.18.3
* npm / yarn version: 6.14.6 / 1.22.4

### Additional Context
The part of Bit installation in Dockerfile

```
FROM node:12-alpine AS bvm

# Install Bvm and Bit for reusable components
RUN yarn global add @teambit/bvm \
  && bvm install \
  && ln -s $HOME/bin/bit /usr/local/bin/ \
  && bit -v
```

And link part

```
# install dependencies
RUN yarn install

# copy bitmap and make links
COPY .bitmap .
RUN bit link
```

**Comment by davidfirst** [comment] 2021-03-24 18:36
@ivansky , I'm not familiar with the docker part here, but as far as I can see `bit link` doesn't use Git. I even tried to change `git` bin on my local and I was able to run `bit link` with no error. 
Maybe it's the next command on Docker? If you do think it's the bit-link, it'd be great if you could run the command wit `--log` and paste the log here.

**Comment by itaymendel** [comment] 2021-03-25 08:16
Perhaps Bit is not properly set on the container? if you used `@teambit/bvm` for installing Bit, make sure to add `$HOME/bin` to your path. Note that by default BVM's link location for the binary is for a specific user on the OS, so its possible you need to change that to a global link location.

**Comment by ivansky** [comment] 2021-03-25 09:37
Hi @davidfirst @itaymendel It might be because the git folder is not there, bit expects workspace in it.
```
#12 51.25 $ bit link
#12 51.63 /bin/sh: git: not found
#12 51.64 /bin/sh: git: not found
#12 51.81 Warning: running bit as root might cause permission issues later
#12 52.86 /bin/sh: git: not found
#12 52.86 /bin/sh: git: not found
#12 52.96 /bin/sh: git: not found
#12 52.97 workspace not found. to initiate a new workspace, please use `bit init`
#12 53.00 error Command failed with exit code 1.
```

Should I add `bit init` command to create workspace? I would not include git folder into Docker context.

**Comment by davidfirst** [comment] 2021-04-01 13:13
@ivansky , Bit doesn't need git folder to init a new workspace. If there is no git in that directory, the scope will be in `.bit` directory, instead of `.git/bit`.
About `bit link`, you can't run it on a non-bit-workspace because it has no meaning.

**Comment by GiladShoham** [comment] 2021-05-04 10:58
I think I fixed it sometime ago, but i'm not sure. 
@ivansky can you please attach a dockerfile so we can easily reproduce it?

**Comment by ivansky** [comment] 2021-05-04 11:59
@GiladShoham I need a few days to get back to bit, will check.

**Comment by ivansky** [comment] 2021-07-06 16:03
I am not sure why, but messages about git is still in docker log:
```
#8 [bvm 4/4] RUN bit config set analytics_reporting false  && bit config set error_reporting false  && bit config set interactive false
#8 sha256:15f68b4f73d87c7246a89fe9fb04cb74af5568a87a400fa1d195fe2751fb5d33
#8 1.682 /bin/sh: git: not found
#8 1.704 /bin/sh: git: not found
#8 2.121 /bin/sh: git: not found
#8 2.145 Warning: running bit as root might cause permission issues later
#8 6.702 /bin/sh: git: not found
#8 6.721 /bin/sh: git: not found
#8 6.755 /bin/sh: git: not found
#8 6.769 /bin/sh: git: not found
#8 6.782 /bin/sh: git: not found
#8 6.865 - running command "set"...
#8 6.873 added configuration successfully
#8 8.030 /bin/sh: git: not found
#8 8.045 /bin/sh: git: not found
#8 8.322 /bin/sh: git: not found
#8 8.341 Warning: running bit as root might cause permission issues later
#8 11.16 /bin/sh: git: not found
#8 11.18 /bin/sh: git: not found
#8 11.19 /bin/sh: git: not found
#8 11.26 - running command "set"...
#8 11.27 added configuration successfully
#8 12.85 /bin/sh: git: not found
#8 12.86 /bin/sh: git: not found
#8 13.24 /bin/sh: git: not found
#8 13.26 Warning: running bit as root might cause permission issues later
#8 16.50 /bin/sh: git: not found
#8 16.52 /bin/sh: git: not found
#8 16.59 - running command "set"...
#8 16.60 added configuration successfully
#8 DONE 16.6s
```

What does it mean?

There is Dockerfile with the first step
```Dockerfile
FROM node:14.16.0-alpine3.11 AS bvm

# Install Bvm and Bit for reusable components
RUN yarn global add @teambit/bvm && bvm install
RUN ln -s ~/bin/bit /usr/local/bin/bit &&  bit -v
#RUN yarn global add @teambit/bit \
#   && ln -s /usr/local/bin/bbit /usr/local/bin/bit \
#   && ln -s /tmp/symphony/etc/.bitrc.jsonc ~/.bitrc.jsonc \
#  && bit -v

# config bit analytics
RUN bit config set analytics_reporting false \
 && bit config set error_reporting false \
# && bit config set no_warnings true \
 && bit config set interactive false
```

**Comment by itaymendel** [comment] 2023-01-08 12:50
i think it's a matter of having git installed in the docker container as well.
for some commands bit uses git behind the scenes.

**Closed by itaymendel** 2023-01-08 12:50 UTC
Labels: type/bug, priority/low
