### ISSUE TITLE
Cannot import or install bit component as no package.json file on remote

### ISSUE THREAD

**Issue by seed-of-apricot** [teambit/bit#2039] opened 2019-09-27 14:50 UTC
Original issue: #2015 

When I try installing or importing [this component](https://bit.dev/chronolapselibrary/components/organisms/header), it shows:

``` node
C:\Users\[user]\src\[user]\chronolapselibrary\client>bit import chronolapselibrary.components/organisms/header
Fatal: There is a mismatch between the remote server version - "14.4.0" and your bit version - "14.3.0", please update   

failed running npm install at C:\Users\[user]\src\[user]\chronolapselibrary\client\src\bit\organisms\header   
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bit/chronolapselibrary.components.atoms.brand-logo@0.1.1 postinstall: `node .bit.postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bit/chronolapselibrary.components.atoms.brand-logo@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2019-09-25T07_01_00_765Z-debug.log

see troubleshooting at https://docs.bit.dev/docs/install-components.html

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

This seems because there's no package.json of one of the dependency at the npm registry, but I'm not sure at all to deal with this issue.  

``` node
C:\Users\[user]\src\[user]\chronolapselibrary\client>npm i @bit/chronolapselibrary.components.atoms/brand-logo
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@bit\chronolapselibrary.components.atoms\brand-logo" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2019-09-27T02_20_23_342Z-debug.log
```

Could anyone please help me out? I'm happy to provide further information if needed, as I did in the previous issue.

**Comment by seed-of-apricot** [comment] 2019-09-29 04:58
This issue might due to the svg asset that I use in the `brand-logo` component.
Reference: [https://github.com/teambit/bit.envs/issues/58](https://github.com/teambit/bit.envs/issues/58)

**Comment by davidfirst** [comment] 2019-10-02 00:36
@seed-of-apricot , I was able to reproduce the issue on my Windows environment. It doesn't happen on Mac.
To debug the issue I ran your import command as follows: `bit import chronolapselibrary.components/organisms/header -- -ignore-scripts`, this way, it didn't run the post-install script and didn't delete the node_modules dir, so I could run it myself.
Once running it, the error I got is `operation not permitted`. See the full error below.

As expected, when I opened the cmd as Administrator, I was able to run it with no issues.

Please let me know if there is anything else needed for this issue, if not, please close it.

```
C:\Users\DAVIDF~1\AppData\Local\Temp\bit\e2e\qw\components\organisms\header\node_modules\@bit\chronolapselibrary.components.atoms.brand-logo>node .bit.postinstall.js
fs.js:114
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'C:\Users\DAVIDF~1\AppData\Local\Temp\bit\e2e\qw\components\organisms\header\node_modules\@bit\chronolapselibrary.assets.images.logo.index\index.svg' -> 'node_modules/@assets/images/logo/index.svg'
    at Object.symlinkSync (fs.js:909:3)
    at C:\Users\DAVIDF~1\AppData\Local\Temp\bit\e2e\qw\components\organisms\header\node_modules\@bit\chronolapselibrary.components.atoms.brand-logo\.bit.postinstall.js:28:8
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\Users\DAVIDF~1\AppData\Local\Temp\bit\e2e\qw\components\organisms\header\node_modules\@bit\chronolapselibrary.components.atoms.brand-logo\.bit.postinstall.js:24:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
```

**Comment by seed-of-apricot** [comment] 2019-10-02 02:20
@davidfirst 
Thank you for reproducing this issue.

So... Why did this happen only with this component?  
Also, isn't it possible to resolve this with the end of bit (is this a problem in the environment of end-user)?

**Comment by GiladShoham** [comment] 2019-10-02 10:37
> Why did this happen only with this component

Two possible reasons I can think of:
1. Only this component has a post-install script generated by bit. We generate this post-install script when a component require another component using absolute paths defined in the `resolveModules` section in the bit config.
2. This component folder hierarchy contains some files/folders created by a root user by another process such as npm, bash script or something else.

It's not really possible to solve it at the end of bit, since creating such symlinks are OS operation, therefore subject to the OS rules.

**Comment by davidfirst** [comment] 2019-10-02 15:46
I'll add to what Gilad mentioned, this component not only has a post-install script, but also the script generates a symlink. 
The reason for generating a symlink and not creating a link-file is that the file has `.svg` extension. (so, it's impossible to create a link file to point to that svg file).

@GiladShoham , we might be able to work around it with the `symlinkOrCopy` lib, but it's not going to be easy because it's in the postinstall script, so it won't make sense to install that package there, only to implement it ourselves.

**Comment by GiladShoham** [comment] 2019-10-03 08:53
Thanks @davidfirst .
Yes, I thought about it, but I don't see it as a strong enough reason to go this path now.
I think it should be handled by the user by fixing the permission issues, it will be faster and safer than adding more mechanisms like a copy in such cases.

**Comment by seed-of-apricot** [comment] 2019-10-04 17:58
@GiladShoham @davidfirst 
Thank you for your further explanation and assessment of the cause.
I was wondering if it is because of the bug in typescript compiler (linked in this thread) but seems more fundamental one.

I hope it will work correctly in someday future, but for now I will go for the administration.

**Comment by GiladShoham** [comment] 2019-10-06 10:46
@seed-of-apricot It doesn't look like it's related to the ts compiler issue (I'll wait for @qballer to take a look at the compiler issue in a few days).

> I hope it will work correctly in someday future

I hope that too, but it's more an issue to Microsoft:)

I'll close this for now, since I don't see anything else we can do with it.
If you think differently, please re-open.

**Closed by GiladShoham** 2019-10-06 10:46 UTC
Labels: type/bug
