### ISSUE TITLE
bit show not recognize dependencies

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#580] opened 2018-01-07 16:34 UTC
This happens when the saveDependenciesAsComponents is false
STR
import a component with dependencies from the hub
run bit show
dependencies is empty

It's also recognize bit's as package dependencies

It will probably affect other processes like auto tagging or even the dependencies array in model.

**Comment by davidfirst** [comment] 2018-01-08 16:50
@GiladShoham, as suspected, the issue is related to the migration from 'bit' to '@bit'.
As a proof, try the same STR with the following component: "david.tests/bar/foo", which has the updated bindingPrefix as @bit.
The output from 'bit show' contains the 'is-string' dependency.
I'm closing this because as I understand you're working on a fix for this in another issue.

**Closed by davidfirst** 2018-01-08 16:50 UTC
Labels: High, bug, show
