### ISSUE TITLE
must have a '[Symbol.iterator]()' method that returns an iterator error

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4100] opened 2021-04-11 20:02 UTC
I have a ts react component that use react-spring. It raise many ts error with useSpring hook when try to tag it

![image](https://user-images.githubusercontent.com/70728456/114319336-ae8e9680-9b19-11eb-87bd-a3bc1da74390.png)
 
It is Harmony version. Any help ?

**Comment by GiladShoham** [comment] 2021-04-14 08:27
can you please provide steps to reproduce? or a project tar file / repo will be even better. 
Thanks.

**Comment by itaymendel** [comment] 2021-05-03 06:23
hi, sadly no STRs, so we can't reproduce the issue.
closing it. please reopen with STRs so we can have a look.

**Closed by itaymendel** 2021-05-03 06:23 UTC
Labels: type/bug
