### ISSUE TITLE
Hard reset doesn't do the job

### ISSUE THREAD

**Issue by boschr** [teambit/bit#1130] opened 2018-07-11 09:20 UTC
## Expected Behavior
After executing `bit init --reset-hard` i expect not to have the following files in my project:
- `.bitmap`
- `bit.json`
- `.bit`

As described at: https://docs.bitsrc.io/docs/cli-init.html

## Actual Behavior
Files are still there.

## Steps to Reproduce the Problem

  1. `mkdir bit-test && cd bit-test`
  1. `bit init`
  1. `bit init --reset-hard`

## Specifications

  - Bit version: 13.0.2
  - Node version: v9.5.0
  - yarn version: v1.3.2
  - Platform: OSX
  - Bit compiler (include version): none
  - Bit tester (include version): none

**Comment by itaymendel** [comment] 2018-07-11 09:52
hi @boschr , thanks for opening this issue.

I'm sorry for the misunderstanding, but the issue is in the docs, not in Bit...
The hard-reset removes the old objects and files and creates a fresh instance of the local Scope.

I'm closing this issue and posting an update to the docs with the correct behavior.

**Closed by itaymendel** 2018-07-11 09:52 UTC

**Comment by boschr** [comment] 2018-07-11 10:01
@itaymendel Thanks for your quick reply. Is it possible to completely remove Bit from a project using the Bit CLI? Or is the only way to remove those 3 files/folders by hand?

I'm relative new to Bit and struggling how to exactly use Bit. Sometimes it is such a mess and i better can start from scratch ;).

**Comment by boschr** [comment] 2018-07-11 12:11
@itaymendel again thanks for your support!

I have a few more questions to understand Bit a 'bit' more ;). It is the intention to create a new issue for this?

**Comment by itaymendel** [comment] 2018-07-11 12:55
@boschr - you are welcome to create issues with questions.

in the next few days, we'll be opening a community forum that will better fit such discussions, however, i don't want to hold you back from learning Bit.
