### ISSUE TITLE
404 on font path in compositions 

### ISSUE THREAD

**Issue by yara-tle** [teambit/bit#4805] opened 2021-08-11 10:19 UTC
When previewing components locally and bit.dev the font path is broken.

![](https://user-images.githubusercontent.com/83707900/129012560-db713931-07ff-410d-8eb3-a2b2eef69554.png)

styles.css: 
![](https://user-images.githubusercontent.com/83707900/129012568-d540d7b5-58a6-420f-b77e-46ccf4cc1c54.png)

In `tailwind-react.preview.runtime.tsx` I import like so:

`import '@yara-dpp/frontend-components.styles.tailwind-styles/dist/styles.css';`

I get correct path to fonts when I install component in a project.

Error locally:

`Failed to decode downloaded font: http://localhost:3000/preview/yara-dpp.frontend-components/envs/tailwind-react@0.0.2/static/css/8bf3a8009b95f29ad673.woff2`

Errors bit.dev:

`GET https://tj0eaqc.scopes.bit.dev/api/yara-dpp.frontend-components/ui/login@0.0.15/~aspect/preview/static/css/188f8558f03121f44d41.woff2 net::ERR_ABORTED 404`

**Comment by KutnerUri** [comment] 2021-09-09 10:55
@yara-tle, @thsvr  - I just upgraded Webpack and others in #4842. It seems to be working now, can you check?

**Comment by yara-tle** [comment] 2021-09-13 15:50
I can confirm this is working on my side with bit v0.0.507

**Comment by KutnerUri** [comment] 2021-09-13 15:53
great, closing. :)

**Closed by KutnerUri** 2021-09-13 15:53 UTC
Labels: type/bug, priority/high

**Comment by KutnerUri** [comment] 2021-10-20 22:37
I think I found it, it might be caused by `publicPath: ""`. I will have to test it thoroughly though
