### ISSUE TITLE
component dependency isn't recognized when import component 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1764] opened 2019-06-26 18:56 UTC
### Describe the bug
on import `qballer.ngx-bootstrap/datepicker` I get (stage) 
```
 > datepicker ...  issues found       
       untracked file dependencies (use "bit add <file>" to track untracked files as components): 
          datepicker/bs-datepicker.spec.ts -> components/datepicker/utils/index.ts
```

### Steps to Reproduce

  1. on stage environment  `bit import qballer.ngx-bootstrap/datepicker`
  2. bit status
  3. status is broken

### Expected Behavior
clean status
### Specifications

  bit version   : 14.1.4-dev.2
  node version  : v12.3.1
  npm version   : 6.9.0
  yarn version  : 1.16.0
  platform      :  linux

**Comment by itaymendel** [comment] 2019-06-26 20:35
@qballer , it seems that when I specifically imported `qballer.ngx-bootstrap/utils@0.0.1` it works, but for some weird reason when I checkout back to `utils@0.0.2` I'm getting the missing dependency issue.

**Comment by davidfirst** [comment] 2019-06-27 01:53
@qballer , turned out it happened because the dependency link was not generated correctly. 
It's `import { registerEscClick } from '@bit/qballer.ngx-bootstrap.utils/dist/utils/index.ts';` while it should be `import { registerEscClick } from '@bit/qballer.ngx-bootstrap.utils';`.

Bit compares the dependency mainFile and the required file and if there is a match the `require` statement is for the module root and not to an internal path in the module. In this case, something weird happened. It shows as if originally datepicker/bs-datepicker.spec.ts required `utils/index.ts` file. However, the main file of `qballer.ngx-bootstrap/utils` is `utils/public_api.ts`. 

I guess I'll need the files you originated these components from to reproduce it from scratch.
For now, I made a quick workaround that replaces the `index.ts` with `public_api.ts`, so then the link is generated correctly.

**Comment by qballer** [comment] 2019-06-30 09:00
https://github.com/valor-software/ngx-bootstrap

**Comment by davidfirst** [comment] 2019-07-01 20:20
I was able to reproduce it by the instruction of https://github.com/teambit/bit/issues/1771, see my comment there for more details.
It has been fixed on https://github.com/teambit/bit/pull/1773 to not include the `.ts` extension in the generated link file.

**Closed** 2019-07-01 23:20 UTC
Labels: area/dependencies, priority/critical, type/bug
