### ISSUE TITLE
bit status hung and killing CPU

### ISSUE THREAD

**Issue by gabaum10** [teambit/bit#1085] opened 2018-06-19 19:21 UTC
## Expected Behavior
`bit status` returns the status of the staged files.  

## Actual Behavior
`bit status` is hung and hammering the CPU.  See htop screenshot:
![bithung](https://user-images.githubusercontent.com/1561245/41619386-08fc3278-73d4-11e8-88fb-8317f2d17625.png)

This started happening after I added the resolveModules config option:

```
"resolveModules": {
    "modulesDirectories": [
      "src"
    ],
    "aliases": {
      "@": "src"
    }
  }
```

## Steps to Reproduce the Problem

  1. Not entirely sure.  Have a complex component tree with many aliased deps and try to add them.  My component has about 20 child components inside it, each of which can import several utility functions and other child components.
  1. Then do `bit status`

## Specifications

  - Bit version: latest
  - Node version: v9.11.1
  - npm / yarn version: yarn 1.7.0
  - Platform: Ubuntu 18.04
  - Bit compiler (include version): latest
  - Bit tester (include version): latest

**Comment by gabaum10** [comment] 2018-06-19 19:37
I'm willing to bet there could be a circular dep in there somewhere.  Does bit not handle circular deps gracefully?

**Comment by itaymendel** [comment] 2018-06-19 19:44
Bit should be able to handle circular deps properly... but perhaps there’s an edge case for it with the aliases. I’ll have to create such structure in a demo project and see.

I do think that the problem is with complex depedency tree. We do know of some internal indexing issues that needs fixing, and should make Bit hog much less resources and be snappier (our goal is for bit to be as fast as git... 

I’m keeping this issue open, as a reference to some of the performance improvements we need to do, and to check for the circular deps issue you suggest.

I hope that by tomorrow i will be able to offer an updated, and more researched response.

**Comment by gabaum10** [comment] 2018-06-19 19:47
Fantastic.  Bit is a pretty neat little project. I'd really like to try and leverage it to incorporate some "beta" components for a new Vue app we are building into our old app for some testing and appreciate the prompt responses!

I'll try and do anything I can to help diagnose this.

**Comment by itaymendel** [comment] 2018-06-20 09:51
I think that for starts, what we'll do is set up a project with several aliases and some mock components with circular dependencies... and go from there. Usually, we use small projects for testing, but perhaps for this case, we'll need to structure something with a little bit more oomph.

@GiladShoham and I will try and figure out if there's any specific data we'll need from your project (assuming that the project at hand is not something you can share access to). We'll share progress and questions as we go.

**Comment by gabaum10** [comment] 2018-06-20 10:44
It's not, but I can help structure a demo project with a similar import structure if you're having a hard time reproducing..

**Comment by itaymendel** [comment] 2018-06-20 11:33
We would appreciate your help recreating a similarly structured project, and share it on github. I believe your mock will be much better.

There’s no need for actual implementation, or working project. Similarly structured project with the dependencies and aliases will be fine, as Bit reads the internal dependency graph of a project.

**Comment by gabaum10** [comment] 2018-06-20 13:00
Sure.  Let me see if I can figure something out more or less. The existing project is pretty complicated so it might be tough, but I'll see if I can find some time.

**Comment by itaymendel** [comment] 2018-06-20 13:10
ok, please keep me posted.

at any case, we are still testing it internally as well, as this is a critical issue. now that version 13.0.0 is out, we are focused more on being more dev-friendly and performance. and keeping this issue in mind.

**Comment by itaymendel** [comment] 2018-08-23 11:02
we know of some performance issues with bit, and will handle it in the very near future.
in the meanwhile, due to the fact that we can't reproduce this specific issue, i'm closing it.

**Closed by itaymendel** 2018-08-23 11:02 UTC
