### ISSUE TITLE
Cannot create react template project due to `local issuer certificate` error

### ISSUE THREAD

**Issue by JoeScho** [teambit/bit#6819] opened 2022-12-21 10:01 UTC
I'm new to Bit so my apologies if this is a user error! 

## Expected Behavior
Can create a project per the react quick start documentation.

## Actual Behavior
Does not create a project.

## Steps to Reproduce the Problem
Following instructions here: https://bit.dev/docs/quick-start/basic-react.
Not on a VPN.

1. Running

```sh
$ bit new basic-react my-basic-react --aspect teambit.community/starters/basic-react
```

1. produces the following error
![](https://user-images.githubusercontent.com/12475501/208873930-c917048b-5351-43bd-bc82-ff7893b9b548.png)

## Specifications
* Bit version: 0.0.888
* Node version: v18.12.1
* npm version: 8.19.2
* Platform: MacOS 13.0.1
* Bit compiler (include version): N/A
* Bit tester (include version): N/A

**Comment by benjgil** [comment] 2023-01-03 12:24
looks like there's a proxy issue 
please see our bvm guide for details of setting proxy config with bit
https://bit.dev/reference/reference/using-bvm

**Comment by itaymendel** [comment] 2023-03-06 11:42
closing the issue as there's no way to reproduce and author abandoned it.

**Closed by itaymendel** 2023-03-06 11:42 UTC
