### ISSUE TITLE
Bit link --target is moving all components as sym links vs. one

### ISSUE THREAD

**Issue by ChristopherHawkes** [teambit/bit#5365] opened 2022-02-04 22:08 UTC
We need a way of being able to run bit link without moving all components in a @scope/project as sym links. 

How are we able to symbolically link a single component?

**Comment by itaymendel** [comment] 2022-02-05 15:54
hi,

I don't fully understand what is it you are trying to do.
It is very possible that you are not using `bit link --target` correctly.
By design it uses symlinks, as it's purpose is to create symlinks to the compiled outputs of components from a Bit-workspace to other non-Bit-workspaces.

I'm closing this issue, as `bit link` behaves as intended.
Please open a feature request with your missing workflow.

**Closed by itaymendel** 2022-02-05 15:54 UTC
Labels: type/bug

**Comment by ChristopherHawkes** [comment] 2022-02-07 22:22
I don't understand why this was closed?   I need the ability to debug a bit component locally, in another project without having to push it to the package server.   If I run `bit link --target` it moves all the components as a symlink.   This causes a lot of issues.  In addition, I can't test the install of a bit component to make sure it's dependencies are being installed correctly (which it appears they may not be).
