### ISSUE TITLE
Exported components on bit.dev are missing styles

### ISSUE THREAD

**Issue by p-l-l** [teambit/bit#4668] opened 2021-07-30 16:08 UTC
### Describe the bug
Exported components on bit.dev are missings styles and default values causing some of them to crash
and others to look differently than the dev server.

### Steps to Reproduce
I could provide a copy of my workspace as there could be multiple files implied.

### Expected Behavior
Exported components to bit.dev should look exactly as the dev server and throw the same errors.

### Screenshots, exceptions and logs
Made sure workspace has no diffs
![image](https://user-images.githubusercontent.com/23360637/127679791-0978e304-8036-4ada-a837-fc5ee3208e32.png)

Here is an example of login-form component on local server
![image](https://user-images.githubusercontent.com/23360637/127679877-5292f983-3b4d-4ef4-9c35-2ebdb282b457.png)

Here is an example of login-form component on bit.dev
![image](https://user-images.githubusercontent.com/23360637/127679972-568edc27-bedd-49c7-be86-a11b5122927e.png)

### Specifications
* Bit version: 0.0.471
* Workspace type: harmony
* Node version: 14.16.0
* npm / yarn version: npm 6.14.11 / yarn 1.22.10
* Platform: Windows 10
* using env teambit.react/react and a custom one.

### Additional context
I am using Material-UI 4.11.4, augmented Theme properties and using a custom function to merge custom defaults values
with other options passed to createMuiTheme.
It looks like something went wrong when applying my theme values, as if the whole customization is not present.

**Comment by GiladShoham** [comment] 2021-07-30 16:43
Can you please check on the composition tab as well on bit.dev?

**Comment by p-l-l** [comment] 2021-07-30 17:54
Here is how it looks on the composition tab
![image](https://user-images.githubusercontent.com/23360637/127692560-53adc63e-c719-4bab-8081-ad44e05332f5.png)

**Comment by p-l-l** [comment] 2021-07-30 18:01
Here is a sample of the component files that seem to cause the issues.. could be also depending on how I used it in my custom environnement, let me know if you need more :)
[themes.zip](https://github.com/teambit/bit/files/6909313/themes.zip)

**Comment by KutnerUri** [comment] 2021-08-02 12:34
That's odd.
It looks like a `flex`, and the color of the button is also different.
I don't have access to the scope, and the zip you added only shows the theme, but not the component or how you applied it.
Can you check the source of the styles? if it's in our code, I will be happy to fix it.

I can think of two explanations: 

1. The component might have been tagged with an old version of bit. Docs and preview are created once during tag, so they could have old styles.  
  I made a change a month ago (#4192), that might make the composition flex, but only the in the docs page.
1. Maybe global styles from another component are effecting this component. For efficiency, tags make a single preview for all components together. So while tagging, another component in the workspace might have corrupted your preview, even if it's gone right now.

In both cases, tagging the component again (`bit tag .../login-form --force`, with latest version) should fix it.

1. Check when the components were tagged (and with what version of bit) I made a change a month (#4192) to how compositions are centered in the docs, so maybe the component just needs to be retagged. (it's a long shot though)
2. Check what styles are effecting the composition. If it's from our code, I will handle it, but it might be from some other component that exposes global styles. It should show up in local workspace though.

**Comment by KutnerUri** [comment] 2021-08-02 12:35
That's odd.
It looks like a `flex`, and the color of the button is also different.
I don't have access to the scope, and the zip you added only shows the theme, but not the component or how you applied it.
Can you check the source of the styles? if it's in our code, I will be happy to fix it.

I can think of two explanations: 

1. The component might have been tagged with an old version of bit. Docs and preview are created once during tag, so they could have old styles.  
  I made a change a month ago (#4192), that might make the composition flex, but only the in the docs page.
1. Maybe global styles from another component are effecting this component. For efficiency, tags make a single preview for all components together. So while tagging, another component in the workspace might have corrupted your preview, even if it's gone right now.

In both cases, tagging the component again (`bit tag .../login-form --force`, with latest version) should fix it.

I suspect it's something else though. please check the source of the styles, or what styles are missing.

**Comment by p-l-l** [comment] 2021-08-02 15:27
I compared local composition vs the one of bit.dev, locally the css-in-js class as a specific name, it seems simplified on bit.dev so the `.SkyLoginForm-marginBottom-6` (login-form component) and `makeStyles-popoverInner-2` (a custom popover) have been both converted to `.jss2` and it clashes. The popover comes from a component in a provider that is registered in .preview.runtime.ts 
![image](https://user-images.githubusercontent.com/23360637/127884178-38a6b9b4-7c3a-4ddf-9bc3-f9c2242ac7af.png)

I will recap how my things work to provide further details, I made a Popover with custom styles like this:
![image](https://user-images.githubusercontent.com/23360637/127883230-77521d14-816a-4d95-a4d3-3b2eb517f6fa.png)
Then, in the component I use `const classes = useStyles();` and use it with e.g. `className={classes.popoverInner}`

This popover is just a tool that I made up so that QA team can pop it up with key binds and switch between available themes.
The provider for preview uses that popover along with my theme provider...
You can see that .jss2 at the bottom (from bit.dev) matches `popoverInner` class

Using my login-form as an example of the issue, this component styles use another approach:
![image](https://user-images.githubusercontent.com/23360637/127885519-90f87979-5b3d-45a8-b8df-3b3f7d79412b.png)
![image](https://user-images.githubusercontent.com/23360637/127885542-48afc49f-c7a2-47de-b73e-d8027380f9f0.png)
![image](https://user-images.githubusercontent.com/23360637/127885574-be8f935a-888a-4b0b-8b9c-93ff0c78c11b.png)

So it seems that on Bit.dev when these classes got simplified (minification process?) it did not consider scoping the classes to each component with a more unique class name.

**Comment by KutnerUri** [comment] 2021-08-02 15:47
interesting.. and these styles are css-in-js, right?
so, it's js minification, which we have, but I'm sure MUI has a mechanism to handle it.

It seems there are many questions about this - https://stackoverflow.com/questions/56619570/react-material-ui-style-classes-from-different-components-conflict-when-served
It's probably caused by multiple version of `material-ui`, a problem that is a little worse with bit.
Incorrect versions may also come from dependencies (including dev, and deeply nested dependencies).

Try moving it to be a peer dep, at your workspace.json, and consider adding it to your env.
Also make sure each component is using the correct version (or range), using `bit show` or the files tab at the component page.
(we don't have a `bit ls` / `bit why` yet, but `pnpm why` / `yarn why` might work)

**Comment by p-l-l** [comment] 2021-08-02 21:06
I made sure that all my components uses @material-ui/core/styles for the [stylings](https://material-ui.com/styles/basics/) and @material-ui/core is a peerDependecy in my workspace.json (was already initially). I also did a fll reuset of the collection (nothing is used yet in any project).
I added it to my env (not 100% sure if it's the appropriate way to do it)
![image](https://user-images.githubusercontent.com/23360637/127923245-fdbdbed4-3fdb-43c3-a3e1-6f70135e28c6.png)

The issues are the same, I will send you a full copy of my project privately, a second look wouldn't hurt 😄

**Comment by KutnerUri** [comment] 2021-08-03 11:08
after some trial and error, it seems to be happening because `ThemeSwitching` is applied via the env `providers`.
So, just apply it directly to the composition. (instead of registering it as a provider).
I will investigate.

also, after review, it's enough to set `@material-ui/core` as peer in the workspace. I'd make it a semver (`^4.0.0`) to allow the component to work in more projects.

**Closed** 2023-03-06 07:26 UTC
Labels: type/bug
