### ISSUE TITLE
bit status => "Unexpected token, expected ( (50:8)

### ISSUE THREAD

**Issue by uptownhr** [teambit/bit#1073] opened 2018-06-16 02:48 UTC
## Expected Behavior
when running bit status, it should show me status

## Actual Behavior
it is erroring out without much info

## Steps to Reproduce the Problem

  1. create directory
  2. add component.vue
  3. add index.js
  4. notice bit status works
  5. start over but this time, include another component2.vue file but not used by component.vue
  6. notice bit status errors

## Specifications

  - Bit version: 0.12.13
  - Node version: 8.8.1
  - npm / yarn version: 5.6.0
  - Platform: ubuntu 16.04
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment] 2018-06-18 14:24
hi @uptownhr , i'm unable to recreate the issue.

any change you can paste here the error and Bit's log file?

https://docs.bitsrc.io/docs/logs.html

**Comment by uptownhr** [comment] 2018-06-20 02:46
will do.

**Comment by itaymendel** [comment] 2018-08-23 11:02
can't reproduce. closing the issue.

**Closed by itaymendel** 2018-08-23 11:02 UTC
Labels: type/bug
